/**
 * Kamen Segway Personal Transporter Physics Kernel (US 6,302,230 B1)
 *
 * Modern illustrative SI model of the source-described self-balancing topology.
 *
 * US 6,302,230 establishes a powered, automatically balanced vehicle, a balancing
 * margin, and an alarm that may use ripple modulation. It does not print a chassis
 * mass, wheel radius, motor rating, controller gains, warning frequency, or a fall
 * trajectory. Those numerical inputs are deliberately identified as an illustrative
 * teaching scenario rather than historical measurements.
 */

export interface KamenSegwayControls {
  /** User pitch lean angle in degrees (-15° aft to +15° fore) */
  riderPitchDeg: number;
  /** Commanded steering yaw rate (-1.0 full left to +1.0 full right) */
  steeringInput: number;
  /** Rider mass in kg (40 to 120 kg) */
  riderMassKg: number;
  /** Ground surface friction coefficient μ (0.15 ice to 0.9 dry pavement) */
  groundFrictionCoeff: number;
  /** Maximum speed governor limit in m/s (2.0 to 6.0 m/s) */
  speedLimitMS: number;
  /** Claim 1 topology probe; false withholds powered automatic balance. */
  claim1BalanceEnabled: boolean;
  /** Claim 2 topology probe; false withholds the ripple-modulation alarm path. */
  claim2RippleEnabled: boolean;
}

export interface KamenSegwayTelemetry {
  /** Forward velocity in m/s */
  velocityMS: number;
  /** Forward velocity in km/h */
  velocityKmh: number;
  /** Forward acceleration in m/s² */
  accelerationMS2: number;
  /** Net restoring motor torque in N·m */
  motorTorqueNm: number;
  /** Left wheel motor torque in N·m */
  leftMotorTorqueNm: number;
  /** Right wheel motor torque in N·m */
  rightMotorTorqueNm: number;
  /** Gravitational overturning torque in N·m */
  gravityOverturningTorqueNm: number;
  /** Ground drive thrust force in N */
  driveThrustForceN: number;
  /** Maximum available ground traction force in N */
  maxTractionForceN: number;
  /** Dimensionless balancing margin ratio (0.0 exhausted to 1.0 full reserve) */
  balancingMarginRatio: number;
  /** Pitch pushback angle in degrees applied by speed limiter */
  pitchPushbackDeg: number;
  /** Tactile ripple vibration amplitude in N·m */
  rippleAlarmAmplitudeNm: number;
  /** Audible alarm active flag */
  audibleAlarmActive: boolean;
  /** Tactile shake alarm active flag */
  tactileAlarmActive: boolean;
  /** Speed pushback active flag */
  speedPushbackActive: boolean;
  /** Claim 1's powered automatic-balance topology is intentionally withheld. */
  claim1BalanceWithheld: boolean;
  /** Claim 2's ripple-modulation path is intentionally withheld. */
  claim2RippleWithheld: boolean;

  /** Typed Refusal: Wheel traction slip / loss of ground grip */
  tractionLossRefusal: boolean;
  /** Typed Refusal: Pitch angle exceeds physical motor torque recovery envelope */
  pitchOverturnRefusal: boolean;
  /** Typed Refusal: Motor current / thermal saturation */
  motorSaturationRefusal: boolean;
  /** Human-readable refusal reason or null */
  refusalReason: string | null;
}

export const KAMEN_SEGWAY_DEFAULT_CONTROLS: KamenSegwayControls = {
  riderPitchDeg: 4.5,
  steeringInput: 0.0,
  riderMassKg: 75.0,
  groundFrictionCoeff: 0.85,
  speedLimitMS: 5.5,
  claim1BalanceEnabled: true,
  claim2RippleEnabled: true,
};

/** Explicit visitor-facing boundary for every number generated by this module. */
export const KAMEN_SEGWAY_MODERN_SCENARIO_BOUNDARY =
  "Modern illustrative SI scenario: US 6,302,230 discloses the balancing topology and alarm relationship, not these numerical hardware parameters or performance values.";

// Modern illustrative scenario constants — none is presented as a value printed by US 6,302,230.
const CHASSIS_MASS_KG = 43.0;
const WHEEL_RADIUS_M = 0.24;
const CG_HEIGHT_M = 0.92;
const GRAVITY_M_S2 = 9.80665;
const MAX_MOTOR_TORQUE_TOTAL_NM = 160.0;
const KV_SPEED = 12.0;

export function readKamenSegwayControls(
  params: Record<string, number | undefined> = {},
): KamenSegwayControls {
  return {
    riderPitchDeg:
      params.riderPitchDeg ??
      params.pitch ??
      params.lean ??
      KAMEN_SEGWAY_DEFAULT_CONTROLS.riderPitchDeg,
    steeringInput:
      params.steeringInput ??
      params.steering ??
      params.yaw ??
      KAMEN_SEGWAY_DEFAULT_CONTROLS.steeringInput,
    riderMassKg:
      params.riderMassKg ??
      params.mass ??
      params.riderMass ??
      KAMEN_SEGWAY_DEFAULT_CONTROLS.riderMassKg,
    groundFrictionCoeff:
      params.groundFrictionCoeff ??
      params.friction ??
      KAMEN_SEGWAY_DEFAULT_CONTROLS.groundFrictionCoeff,
    speedLimitMS:
      params.speedLimitMS ?? params.speedLimit ?? KAMEN_SEGWAY_DEFAULT_CONTROLS.speedLimitMS,
    claim1BalanceEnabled:
      (params.claim1BalanceEnabled ??
        params.balanceEnabled ??
        (KAMEN_SEGWAY_DEFAULT_CONTROLS.claim1BalanceEnabled ? 1 : 0)) >= 0.5,
    claim2RippleEnabled:
      (params.claim2RippleEnabled ??
        params.rippleEnabled ??
        (KAMEN_SEGWAY_DEFAULT_CONTROLS.claim2RippleEnabled ? 1 : 0)) >= 0.5,
  };
}

export function stepKamenSegwaySi(controls: KamenSegwayControls): KamenSegwayTelemetry {
  const totalMassKg = controls.riderMassKg + CHASSIS_MASS_KG;
  const normalForceN = totalMassKg * GRAVITY_M_S2;
  const maxTractionForceN = controls.groundFrictionCoeff * normalForceN;

  // Pitch angle in radians
  const pitchRad = (controls.riderPitchDeg * Math.PI) / 180;

  // Overturning gravitational torque: tau_grav = M * g * L * sin(theta)
  const gravityOverturningTorqueNm = totalMassKg * GRAVITY_M_S2 * CG_HEIGHT_M * Math.sin(pitchRad);

  // Equilibrium forward velocity is a modern illustrative mapping from lean to motion.
  let nominalVelocityMS = controls.claim1BalanceEnabled
    ? (controls.riderPitchDeg / 15.0) * controls.speedLimitMS
    : 0;

  // Speed limiting pushback: if nominal speed exceeds governor limit
  let pitchPushbackDeg = 0.0;
  let speedPushbackActive = false;
  if (controls.claim1BalanceEnabled && Math.abs(nominalVelocityMS) > controls.speedLimitMS * 0.9) {
    speedPushbackActive = true;
    const overspeed = Math.abs(nominalVelocityMS) - controls.speedLimitMS * 0.9;
    pitchPushbackDeg = Math.sign(nominalVelocityMS) * Math.min(6.0, overspeed * 3.5);
    nominalVelocityMS =
      Math.sign(nominalVelocityMS) *
      Math.min(controls.speedLimitMS, Math.abs(nominalVelocityMS) * 0.95);
  }

  // Restoring torque required to balance the inverted pendulum
  // tau_motor = M*g*L*sin(theta) + K_v * v
  const motorTorqueNm = controls.claim1BalanceEnabled
    ? gravityOverturningTorqueNm + KV_SPEED * nominalVelocityMS
    : 0;

  // Differential steering torque
  const steeringDeltaTorque = controls.claim1BalanceEnabled ? controls.steeringInput * 18.0 : 0;
  const leftMotorTorqueNm = motorTorqueNm / 2 - steeringDeltaTorque;
  const rightMotorTorqueNm = motorTorqueNm / 2 + steeringDeltaTorque;

  // Drive thrust force at the wheel contact patch: F = tau / R
  const driveThrustForceN = motorTorqueNm / WHEEL_RADIUS_M;

  // Forward acceleration: a = F_drive / totalMass
  const accelerationMS2 = driveThrustForceN / totalMassKg;

  // Balancing margin calculation (US 6,302,230 Col. 13-14)
  // Difference between maximum motor acceleration potential and currently demanded acceleration
  const torqueFraction = Math.min(1.0, Math.abs(motorTorqueNm) / MAX_MOTOR_TORQUE_TOTAL_NM);
  const velocityFraction = Math.min(1.0, Math.abs(nominalVelocityMS) / controls.speedLimitMS);
  const balancingMarginRatio = controls.claim1BalanceEnabled
    ? Math.max(0.0, 1.0 - 0.55 * torqueFraction - 0.45 * velocityFraction)
    : 0;

  // Alarms: low balancing margin triggers audible and tactile ripple shudder alarms
  const lowMargin = controls.claim1BalanceEnabled && balancingMarginRatio < 0.22;
  const audibleAlarmActive = lowMargin || speedPushbackActive;
  const tactileAlarmActive = controls.claim2RippleEnabled && (lowMargin || speedPushbackActive);
  const rippleAlarmAmplitudeNm = tactileAlarmActive ? 9.5 : 0.0;

  // Typed Refusal Boundaries
  let tractionLossRefusal = false;
  let pitchOverturnRefusal = false;
  let motorSaturationRefusal = false;
  let refusalReason: string | null = null;

  if (!controls.claim1BalanceEnabled) {
    pitchOverturnRefusal = true;
    refusalReason =
      "Claim 1 topology withheld: the grant says the unpowered system is unstable with respect to tipping. This comparison makes no fall-time or hardware-performance prediction.";
  } else if (Math.abs(controls.riderPitchDeg) > 18.0) {
    pitchOverturnRefusal = true;
    refusalReason = `Pitch angle (${controls.riderPitchDeg.toFixed(1)}°) exceeds recovery envelope; gravitational torque (${Math.abs(gravityOverturningTorqueNm).toFixed(0)} N·m) overcomes motor balancing authority.`;
  } else if (Math.abs(driveThrustForceN) > maxTractionForceN) {
    tractionLossRefusal = true;
    refusalReason = `Wheel traction lost: demanded drive thrust (${Math.abs(driveThrustForceN).toFixed(0)} N) exceeds tire grip limit (${maxTractionForceN.toFixed(0)} N, μ=${controls.groundFrictionCoeff}).`;
  } else if (Math.abs(motorTorqueNm) > MAX_MOTOR_TORQUE_TOTAL_NM * 1.05) {
    motorSaturationRefusal = true;
    refusalReason = `Motor torque saturated: demanded torque (${Math.abs(motorTorqueNm).toFixed(1)} N·m) exceeds dual-motor peak rating (${MAX_MOTOR_TORQUE_TOTAL_NM} N·m).`;
  }

  return {
    velocityMS: nominalVelocityMS,
    velocityKmh: nominalVelocityMS * 3.6,
    accelerationMS2,
    motorTorqueNm,
    leftMotorTorqueNm,
    rightMotorTorqueNm,
    gravityOverturningTorqueNm,
    driveThrustForceN,
    maxTractionForceN,
    balancingMarginRatio,
    pitchPushbackDeg,
    rippleAlarmAmplitudeNm,
    audibleAlarmActive,
    tactileAlarmActive,
    speedPushbackActive,
    claim1BalanceWithheld: !controls.claim1BalanceEnabled,
    claim2RippleWithheld: !controls.claim2RippleEnabled,
    tractionLossRefusal,
    pitchOverturnRefusal,
    motorSaturationRefusal,
    refusalReason,
  };
}
