/**
 * Private 3D slider names → registry control ids.
 * 3D files keep reverting to local keys; the bus stores the canonical id
 * and expands the alias on read so both faces stay on one number.
 */

export interface ParamAlias {
  canonical: string;
  toCanonical?: (aliasValue: number) => number;
  fromCanonical?: (canonicalValue: number) => number;
}

const same = (canonical: string): ParamAlias => ({ canonical });

/** Per-patent alias map. Linde remains peer-owned. */
export const PATENT_PARAM_ALIASES: Record<string, Record<string, ParamAlias>> = {
  "us-542846-diesel-engine": {
    compressionRatio: same("compRatio"),
    cr: same("compRatio"),
    cutoff: same("cutoffRatio"),
    rc: same("cutoffRatio"),
    blastAirPressureBar: same("blastAirPressure"),
    blastPressure: same("blastAirPressure"),
    pBlast: same("blastAirPressure"),
    pBlastBar: same("blastAirPressure"),
    rpm: same("engineRpm"),
    speedRpm: same("engineRpm"),
  },
  "us-3237-rillieux-evaporator": {
    juiceFeedRate: same("juiceFeedRateKgPerH"),
    feedRate: same("juiceFeedRateKgPerH"),
    feedRateKgPerH: same("juiceFeedRateKgPerH"),
    initialBrix: same("initialBrixDeg"),
    brixIn: same("initialBrixDeg"),
    rawBrix: same("initialBrixDeg"),
    targetBrix: same("targetBrixDeg"),
    brixOut: same("targetBrixDeg"),
    syrupBrix: same("targetBrixDeg"),
    effects: same("numberOfEffects"),
    nEffects: same("numberOfEffects"),
    stages: same("numberOfEffects"),
  },
  "us-3633-goodyear-rubber": {
    vulcanizationTempC: same("vulcanTemp"),
    cureTemp: same("vulcanTemp"),
    temperatureC: same("vulcanTemp"),
    vulcanTempC: same("vulcanTemp"),
    sulfur: same("sulfurPct"),
    sulfurPercentage: same("sulfurPct"),
    sulfurRatioPct: same("sulfurPct"),
    specimenTemp: same("specimenTempC"),
    testTempC: same("specimenTempC"),
    ambientTempC: same("specimenTempC"),
    stretch: same("appliedTensileStretch"),
    lambda: same("appliedTensileStretch"),
    tensileStretch: same("appliedTensileStretch"),
  },
  "us-174465-bell-telephone": {
    voiceAmpDb: same("voiceAmplitude"),
    splDb: same("voiceAmplitude"),
    spl: same("voiceAmplitude"),
    voiceLevelDb: same("voiceAmplitude"),
    soundPressureDb: same("voiceAmplitude"),
    voiceDb: same("voiceAmplitude"),
    frequencyHz: same("acousticFrequencyHz"),
    voiceFreq: same("acousticFrequencyHz"),
    freqHz: same("acousticFrequencyHz"),
    frequency: same("acousticFrequencyHz"),
    freq: same("acousticFrequencyHz"),
    audioFreq: same("acousticFrequencyHz"),
    gapMm: same("airGap"),
    airGapMm: same("airGap"),
    magneticGap: same("airGap"),
    gap: same("airGap"),
    diaphragmGapMm: same("airGap"),
    volts: same("batteryVoltage"),
    voltage: same("batteryVoltage"),
    batteryV: same("batteryVoltage"),
    conductivity: same("liquidConductivity"),
    liquidConductance: same("liquidConductivity"),
    liquidSigma: same("liquidConductivity"),
    sigma: same("liquidConductivity"),
  },
  "us-194047-otto-engine": {
    cr: same("compressionRatio"),
    rpm: same("engineRpm"),
    speedRpm: same("engineRpm"),
    chargeGrading: same("claim1ChargeGradingPresent"),
    claim1: same("claim1ChargeGradingPresent"),
  },
  "us-319596-maxim-machine-gun": { fireRateRpm: same("firingRate") },
  "us-124404-westinghouse-air-brake": {
    trainPipePressurePsi: same("trainPipePressure"),
    brakePressurePsi: same("trainPipePressure"),
    brakePipePressure: same("trainPipePressure"),
    pipePressure: same("trainPipePressure"),
    reservoirPipePressurePsi: same("reservoirPipePressure"),
    reservoirPressure: same("reservoirPipePressure"),
    signalPulsePressurePsi: same("signalPulsePressure"),
    signalPulse: same("signalPulsePressure"),
    signalPressure: same("signalPulsePressure"),
    selectingCock: same("selectingCockPosition"),
    cockPosition: same("selectingCockPosition"),
    cockD1: same("selectingCockPosition"),
    trip: same("accidentTrip"),
    tripCock: same("accidentTrip"),
    cockE: same("accidentTrip"),
  },
  "us-347140-thomson-welding": { currentAmperes: same("weldCurrentAmps") },
  "us-105338-hyatt-celluloid": {
    tempCelsius: same("steamTempC"),
    ramPressurePsi: {
      canonical: "hydraulicPressureMpa",
      // PSI → MPa
      toCanonical: (psi) => Number((psi / 145.038).toFixed(4)),
      fromCanonical: (mpa) => Number((mpa * 145.038).toFixed(1)),
    },
  },
  "us-78317-nobel-dynamite": {
    ngConcentration: same("ngConcentrationPct"),
    ngPercentage: same("ngConcentrationPct"),
    ngPct: same("ngConcentrationPct"),
    nitroglycerinRatioPct: same("ngConcentrationPct"),
    absorption: same("ngConcentrationPct"),
    capEnergy: same("capEnergyJoules"),
    capEnergyJ: same("capEnergyJoules"),
    capJoules: same("capEnergyJoules"),
    primerEnergy: same("capEnergyJoules"),
  },
  "us-135245-pasteur-fermentation": { tempCelsius: same("wortTempC") },
  "us-247804-delaval-separator": {
    feedRateLph: same("rawMilkFlowLph"),
    flow: same("rawMilkFlowLph"),
    milkFlowLph: same("rawMilkFlowLph"),
    feedFlow: same("rawMilkFlowLph"),
    rotorRpm: same("bowlRpm"),
    rpm: same("bowlRpm"),
    speed: same("bowlRpm"),
  },
  "us-682690-hewitt-mercury-lamp": {
    voltage: same("mainsVoltageV"),
    vMains: same("mainsVoltageV"),
    arcVoltage: same("mainsVoltageV"),
    tubeLength: same("tubeLengthCm"),
    length: same("tubeLengthCm"),
    ballast: same("ballastResistanceOhms"),
    ballastOhms: same("ballastResistanceOhms"),
    rBallast: same("ballastResistanceOhms"),
    arcCurrent: same("ballastResistanceOhms"),
    diameter: same("tubeDiameterMm"),
    tubeDiameter: same("tubeDiameterMm"),
    tubeDiamMm: same("tubeDiameterMm"),
    diamMm: same("tubeDiameterMm"),
  },
  "us-821393-wright-flyer": {
    speed: same("airspeed"),
    airspeedMph: same("airspeed"),
    airspeedKts: same("airspeed"),
    warp: same("wingWarp"),
    wingWarpDeg: same("wingWarp"),
    rudderDeg: same("rudder"),
    rudderAngle: same("rudder"),
    elevatorDeg: same("elevator"),
    canard: same("elevator"),
    canardDeg: same("elevator"),
    pitchAngle: same("elevator"),
    coupling: same("coupled"),
    claim18Coupled: same("coupled"),
    rudderInterlock: same("coupled"),
  },
  "us-727650-linde-air-liquefaction": {
    pressure: same("inletPressureAtm"),
    inletPressure: same("inletPressureAtm"),
    throttlePressureBar: same("inletPressureAtm"),
    pHigh: same("inletPressureAtm"),
    coolerTempC: same("coolerOutletC"),
    temperature: same("coolerOutletC"),
    tCooler: same("coolerOutletC"),
  },
  "us-200521-edison-phonograph": {
    cylinderRpm: same("mandrelRpm"),
    rpm: same("mandrelRpm"),
    mandrelSpeed: same("mandrelRpm"),
    speed: same("mandrelRpm"),
    clockworkRpm: same("mandrelRpm"),
    voiceVolume: same("voiceVolumeDb"),
    volumeDb: same("voiceVolumeDb"),
    volume: same("voiceVolumeDb"),
    diaphragmExcitation: same("voiceVolumeDb"),
    spl: same("voiceVolumeDb"),
  },
  "us-x8277-mccormick-reaper": {
    groundSpeedMph: same("forwardSpeedMph"),
    draftSpeedMph: same("forwardSpeedMph"),
  },
  "us-2524035-bardeen-transistor": {
    pointSpacing: same("pointSpacingMils"),
    spacing: same("pointSpacingMils"),
    spacingMils: same("pointSpacingMils"),
    contactSpacing: same("pointSpacingMils"),
    pointSpacingMils: same("pointSpacingMils"),
    sample: same("operatingSample"),
    sampleNumber: same("operatingSample"),
    tableSample: same("operatingSample"),
    sampleIndex: same("operatingSample"),
    operatingSample: same("operatingSample"),
    claim1: same("claim1Active"),
    collectorActive: same("claim1Active"),
    collectorPresent: same("claim1Active"),
    claim1Collector: same("claim1Active"),
  },
  "us-x9430-colt-revolver": {
    cockingTravel: same("cockingTravelPct"),
    cocking: same("cockingTravelPct"),
    travelPct: same("cockingTravelPct"),
    travel: same("cockingTravelPct"),
    chamber: same("chamberIndex"),
    ward: same("chamberIndex"),
    wardIndex: same("chamberIndex"),
  },
  "us-31128-otis-elevator": {
    cableTensionPct: same("cableTension"),
    command: same("driveCommand"),
    direction: same("driveCommand"),
    displayRate: same("displayRatePct"),
    ratePct: same("displayRatePct"),
    ropeIntegrity: same("ropeGIntegrityPct"),
    ropeGIntegrity: same("ropeGIntegrityPct"),
    ropeIntegrityPct: same("ropeGIntegrityPct"),
    stopRope: same("stopRopePulled"),
  },
  "us-586193-marconi-radio": {
    mastHeightM: same("aerialHeight"),
    sparkVoltageKv: same("sparkVoltage"),
  },
  "us-120057-gramme-dynamo": {
    rotorRpm: same("shaftRate"),
    shaftRpm: same("shaftRate"),
    rate: same("shaftRate"),
    shaftRateFactor: same("shaftRate"),
    speed: same("shaftRate"),
  },
  "us-381968-tesla-motor": {
    freq: same("frequency"),
    freqHz: same("frequency"),
    frequencyHz: same("frequency"),
    lineFrequency: same("frequency"),
    lineFreq: same("frequency"),
    hum: same("acHum"),
    audioHum: same("acHum"),
    audio: same("acHum"),
  },
  "us-400766-hall-aluminium": {
    current: same("currentAmperes"),
    amperes: same("currentAmperes"),
    currentA: same("currentAmperes"),
    tempC: same("bathTemperatureCelsius"),
    temperatureCelsius: same("bathTemperatureCelsius"),
    bathTemp: same("bathTemperatureCelsius"),
    bathTempC: same("bathTemperatureCelsius"),
    aluminaPct: same("aluminaConcentrationPct"),
    aluminaConcentration: same("aluminaConcentrationPct"),
    alumina: same("aluminaConcentrationPct"),
  },
  "us-395781-hollerith-tabulating": { tabulatingSpeed: same("cardsPerMin") },
  "us-6162-corliss-steam-engine": {
    boilerPressure: same("steamPressurePsi"),
    boilerPressurePsi: same("steamPressurePsi"),
    cutoff: same("cutoffPct"),
    cutoffPercentage: same("cutoffPct"),
    cutoffRatioPct: same("cutoffPct"),
    pressure: same("steamPressurePsi"),
    rpm: same("engineRpm"),
  },
  "us-79265-sholes-typewriter": { typingWpm: same("typingSpeedWpm") },
  "us-132-davenport-electric-motor": {
    rotorRpm: {
      canonical: "batteryVoltage",
      toCanonical: (rpm) => (rpm / 450) * 12,
      fromCanonical: (volts) => (volts / 12) * 450,
    },
    voltage: same("batteryVoltage"),
    batteryVolts: same("batteryVoltage"),
    v: same("batteryVoltage"),
    torque: same("loadTorque"),
    load: same("loadTorque"),
    torqueNm: same("loadTorque"),
  },
  "us-157124-glidden-barbed-wire": {
    machineRpm: {
      canonical: "twistsPerFoot",
      toCanonical: (rpm) => Math.max(2, Math.min(10, rpm / 24)),
      fromCanonical: (twists) => twists * 24,
    },
    tension: same("wireTensionN"),
    tensionN: same("wireTensionN"),
    lineTensionN: same("wireTensionN"),
    twists: same("twistsPerFoot"),
    twistRate: same("twistsPerFoot"),
    pushForce: same("animalPushForceN"),
    pushForceN: same("animalPushForceN"),
    push: same("animalPushForceN"),
  },
  "us-621195-zeppelin-airship": {
    airspeedMph: {
      canonical: "flightSpeedKnots",
      toCanonical: (mph) => mph * 0.868976,
      fromCanonical: (kn) => kn * 1.15078,
    },
    inflation: same("gasInflation"),
    gasInflationPct: same("gasInflation"),
    inflationPct: same("gasInflation"),
    speed: same("flightSpeedKnots"),
    speedKnots: same("flightSpeedKnots"),
    airspeedKnots: same("flightSpeedKnots"),
    flightSpeed: same("flightSpeedKnots"),
    trim: same("trimWeight"),
    trimWeightPosM: same("trimWeight"),
    ballast: same("trimWeight"),
    altitude: same("flightAlt"),
    altitudeM: same("flightAlt"),
    alt: same("flightAlt"),
  },
  "us-470918-reno-escalator": {
    speedFpm: {
      canonical: "beltSpeed",
      toCanonical: (fpm) => (fpm * 0.3048) / 60,
      fromCanonical: (mps) => (mps * 60) / 0.3048,
    },
  },
  "us-388850-eastman-kodak": {
    shutterSpeed: {
      canonical: "shutterSpeed",
      toCanonical: (v) => (v > 1 ? 1 / v : v),
    },
    subjectDistance: same("subjectDist"),
  },
  "us-235199-bell-photophone": {
    distanceM: same("transmissionDistanceM"),
    distance: same("transmissionDistanceM"),
    rangeM: same("transmissionDistanceM"),
    transmissionDistance: same("transmissionDistanceM"),
    splDb: same("voiceSplDb"),
    spl: same("voiceSplDb"),
    voiceVolume: same("voiceSplDb"),
    voiceLevelDb: same("voiceSplDb"),
    soundLevelDb: same("voiceSplDb"),
    solarIrradiance: same("solarIrradianceWPerM2"),
    irradiance: same("solarIrradianceWPerM2"),
    beamPowerWatts: same("solarIrradianceWPerM2"),
    beamPower: same("solarIrradianceWPerM2"),
    collectorDiameter: same("collectorDiameterM"),
    apertureDiameterM: same("collectorDiameterM"),
    apertureDiameter: same("collectorDiameterM"),
    collectorDiam: same("collectorDiameterM"),
  },
  "us-313224-mergenthaler-linotype": {
    castingLpm: {
      canonical: "matrixRate",
      toCanonical: (lpm) => lpm * 42,
      fromCanonical: (cpm) => cpm / 42,
    },
    matrixRatePerMin: same("matrixRate"),
    typesettingSpeed: same("matrixRate"),
    matrixSpeed: same("matrixRate"),
    spacebandWedgeMm: same("spacebandWedge"),
    wedge: same("spacebandWedge"),
    wedgeMm: same("spacebandWedge"),
    potTempC: same("potTemp"),
    metalTemp: same("potTemp"),
    temperatureC: same("potTemp"),
    columnMeasurePicas: same("lineLengthPicas"),
    lineLength: same("lineLengthPicas"),
    measurePicas: same("lineLengthPicas"),
  },
  "us-328710-parsons-turbine": {
    steamPressureBar: {
      canonical: "inletPressurePsi",
      toCanonical: (bar) => bar * 14.5038,
      fromCanonical: (psi) => psi / 14.5038,
    },
    rpm: same("rotorRpm"),
    turbineRpm: same("rotorRpm"),
    pressure: same("inletPressurePsi"),
  },
  "us-971501-haber-ammonia": {
    synthesisPressureBar: {
      canonical: "pressureAtm",
      toCanonical: (bar) => bar / 1.01325,
      fromCanonical: (atm) => atm * 1.01325,
    },
    pressure: same("pressureAtm"),
    synthesisTempC: same("temperatureCelsius"),
    temp: same("temperatureCelsius"),
    temperature: same("temperatureCelsius"),
    feedFlow: same("feedFlowRateMolesPerSec"),
    activity: same("catalystActivity"),
  },
  "us-608969-parsons-turbine": {
    steamPressureBar: {
      canonical: "inletPressurePsi",
      toCanonical: (bar) => bar * 14.5038,
      fromCanonical: (psi) => psi / 14.5038,
    },
  },
  "us-3923554-boyle-smith-ccd": { clockSpeedFactor: same("clockStepRateHz") },
  "us-3858232-boyle-smith-ccd": { clockSpeedFactor: same("clockStepRateHz") },
  "us-1781541-einstein-refrigerator": { auxiliaryGasRatio: same("ammoniaRatio") },
  "us-808897-carrier-air-conditioner": {
    airflow: same("airflowCfm"),
    airFlowCfm: same("airflowCfm"),
    airFlow: same("airflowCfm"),
    flowRateCfm: same("airflowCfm"),
    cfm: same("airflowCfm"),
    sprayRate: same("sprayRatePct"),
    spray: same("sprayRatePct"),
    sprayPct: same("sprayRatePct"),
    nozzleRate: same("sprayRatePct"),
    plateFaces: same("separatorFaces"),
    faces: same("separatorFaces"),
    separatorFaceCount: same("separatorFaces"),
    plates: same("separatorFaces"),
    turns: same("separatorFaces"),
    baffles: same("separatorFaces"),
  },
  "us-2292387-lamarr-frequency-hopping": {
    position: same("recordPosition"),
    pos: same("recordPosition"),
    recordIndex: same("recordPosition"),
    tapePosition: same("recordPosition"),
    row: same("recordPosition"),
    tone: same("commandTone"),
    toneCycles: same("commandTone"),
    frequencyHz: same("commandTone"),
    toneHz: same("commandTone"),
    channels: same("activeChannels"),
    activeChannels: same("activeChannels"),
    numChannels: same("activeChannels"),
    channelCount: same("activeChannels"),
  },
  "us-2708656-fermi-reactor": {
    controlRodWithdrawalPct: same("rodWithdrawal"),
    rodPosition: same("rodWithdrawal"),
    rod: same("rodWithdrawal"),
    controlRod: same("rodWithdrawal"),
    withdrawal: same("rodWithdrawal"),
    moderatorPurityPct: same("moderatorPurity"),
    graphitePurity: same("moderatorPurity"),
    purity: same("moderatorPurity"),
    claim1: same("claim1Active"),
    lattice: same("claim1Active"),
  },
  "us-6469-lincoln-buoy": {
    bellowsInflationPct: same("inflationPct"),
    bellowsExpansionPercent: same("inflationPct"),
    inflation: same("inflationPct"),
    expansionPct: same("inflationPct"),
    steamboatWeightTons: same("weightTons"),
    vesselCargoTons: same("weightTons"),
    weight: same("weightTons"),
    riverShoalDepthFt: same("shoalDepth"),
    riverDepthFeet: same("shoalDepth"),
    depth: same("shoalDepth"),
    depthFt: same("shoalDepth"),
  },
  "us-4750-howe-sewing-machine": {
    rpm: same("crankRpm"),
    speed: same("crankRpm"),
    sewingSpeedRpm: same("crankRpm"),
    stitchingSpeedRpm: same("crankRpm"),
    pitch: same("stitchPitchMm"),
    feedPitch: same("stitchPitchMm"),
    feedPitchMm: same("stitchPitchMm"),
    slack: same("loopSlackPct"),
    slackPct: same("loopSlackPct"),
    cranking: same("isCranking"),
  },
  "us-706737-fessenden-wireless": {
    carrierFreqKhz: same("carrierFrequencyKhz"),
    carrierFreq: same("carrierFrequencyKhz"),
    frequencyKhz: same("carrierFrequencyKhz"),
    frequency: same("carrierFrequencyKhz"),
    audioModPct: same("audioModulationPct"),
    modulationPct: same("audioModulationPct"),
    modulation: same("audioModulationPct"),
    modDepthPct: same("audioModulationPct"),
    modDepth: same("audioModulationPct"),
    tuningUh: same("antennaTuningUh"),
    tuningInductanceUh: same("antennaTuningUh"),
    inductanceUh: same("antennaTuningUh"),
    antennaInductanceUh: same("antennaTuningUh"),
    tuningCoilUh: same("antennaTuningUh"),
    distanceKm: same("transmissionDistanceKm"),
    distance: same("transmissionDistanceKm"),
    rangeKm: same("transmissionDistanceKm"),
  },
  "us-2297691-carlson-electrophotography": {
    exposure: same("exposureLuxSec"),
    exposureSec: same("exposureLuxSec"),
    luxSec: same("exposureLuxSec"),
    opticalExposure: same("exposureLuxSec"),
    thickness: same("layerThicknessUm"),
    layerThickness: same("layerThicknessUm"),
    thicknessUm: same("layerThicknessUm"),
    seleniumThicknessUm: same("layerThicknessUm"),
    temperature: same("fuserTemperatureC"),
    fuserTemp: same("fuserTemperatureC"),
    fuserTempC: same("fuserTemperatureC"),
    fuserTemperature: same("fuserTemperatureC"),
    rollTempC: same("fuserTemperatureC"),
    coronaVoltage: same("coronaVoltageKv"),
    coronaKv: same("coronaVoltageKv"),
    gridVoltage: same("coronaVoltageKv"),
    voltageKv: same("coronaVoltageKv"),
  },
  "us-942699-baekeland-bakelite": {
    temp: same("curingTempC"),
    temperature: same("curingTempC"),
    curingTemp: same("curingTempC"),
    cureTemp: same("curingTempC"),
    autoclaveTempC: same("curingTempC"),
    autoclaveTemp: same("curingTempC"),
    autoclaveTemperature: same("curingTempC"),
    pressure: same("autoclavePressurePsi"),
    pressurePsi: same("autoclavePressurePsi"),
    autoclavePressure: same("autoclavePressurePsi"),
    vesselPressure: same("autoclavePressurePsi"),
    vesselPressurePsi: same("autoclavePressurePsi"),
    catalyst: same("catalystPct"),
    catalystPercent: same("catalystPct"),
    catPct: same("catalystPct"),
    catalystConcentration: same("catalystPct"),
    time: same("curingTimeMin"),
    timeMin: same("curingTimeMin"),
    curingTime: same("curingTimeMin"),
    durationMin: same("curingTimeMin"),
    cureTime: same("curingTimeMin"),
    filler: same("fillerPct"),
    fillerPercent: same("fillerPct"),
    woodFlourPct: same("fillerPct"),
  },
  "us-588-ericsson-propeller": { pitchAngleDeg: same("bladePitchAngleDeg") },
  "us-593138-tesla-coil": {
    frequency: same("disturbanceFrequencyHz"),
    frequencyHz: same("disturbanceFrequencyHz"),
    freq: same("disturbanceFrequencyHz"),
    freqHz: same("disturbanceFrequencyHz"),
    disturbanceFreqHz: same("disturbanceFrequencyHz"),
    disturbanceFreq: same("disturbanceFrequencyHz"),
    secondaryLength: same("secondaryLengthMiles"),
    secondaryLengthMi: same("secondaryLengthMiles"),
    lengthMiles: same("secondaryLengthMiles"),
    wireLength: same("secondaryLengthMiles"),
    wireLengthMiles: same("secondaryLengthMiles"),
    claim1: same("claim1CommonNodeConnected"),
    claim1Active: same("claim1CommonNodeConnected"),
    commonNode: same("claim1CommonNodeConnected"),
    earthNode: same("claim1CommonNodeConnected"),
    groundNode: same("claim1CommonNodeConnected"),
    nodeConnected: same("claim1CommonNodeConnected"),
  },
  "us-36836-gatling-gun": {
    rpm: same("crankRpm"),
    speed: same("crankRpm"),
    crankSpeed: same("crankRpm"),
    handCrankRpm: same("crankRpm"),
    barrels: same("barrelCount"),
    numBarrels: same("barrelCount"),
    count: same("barrelCount"),
  },
  "us-613809-tesla-teleautomaton": {
    rudderAngleDeg: same("rudderAngle"),
    rudder: same("rudderAngle"),
    rudderDeg: same("rudderAngle"),
    steeringAngle: same("rudderAngle"),
    transmitterFreqKhz: same("rfFrequency"),
    carrierFreqKhz: same("rfFrequency"),
    freq: same("rfFrequency"),
    frequency: same("rfFrequency"),
    rfFreqKhz: same("rfFrequency"),
    carrierFrequency: same("rfFrequency"),
    throttle: same("propellerThrottlePct"),
    throttlePct: same("propellerThrottlePct"),
    motorThrottle: same("propellerThrottlePct"),
    propellerThrottle: same("propellerThrottlePct"),
    pulses: same("pulseCount"),
    commandPulses: same("pulseCount"),
    pulsesCount: same("pulseCount"),
    steps: same("pulseCount"),
  },
  "us-1647-morse-telegraph": {
    lineVoltage: same("lineVoltageV"),
    voltage: same("lineVoltageV"),
    keyClosed: same("keyClosed"),
    key: same("keyClosed"),
    current: same("currentMa"),
    lineCurrentMa: same("currentMa"),
    currentMa: same("currentMa"),
    lineResistance: same("lineLengthMiles"),
    lineDistance: same("lineLengthMiles"),
    distanceMiles: same("lineLengthMiles"),
    resistance: same("lineResistanceOhms"),
    wpm: same("wpmSpeed"),
    speed: same("wpmSpeed"),
    turns: same("wireTurns"),
  },
  "us-1102653-goddard-rocket": {
    ratio: same("tubeLengthRatio"),
    ldRatio: same("tubeLengthRatio"),
    aspectRatio: same("tubeLengthRatio"),
    primarySpin: same("primarySpinRpm"),
    spinRpm: same("primarySpinRpm"),
    primaryRpm: same("primarySpinRpm"),
    gyroSpin: same("gyroSpinRpm"),
    gyroRpm: same("gyroSpinRpm"),
    releaseFraction: same("auxiliaryReleaseFraction"),
    auxRelease: same("auxiliaryReleaseFraction"),
    stagingFraction: same("auxiliaryReleaseFraction"),
    chargeConsumed: same("primaryChargeConsumed"),
    primaryConsumed: same("primaryChargeConsumed"),
    gyro: same("gyroEnabled"),
    hasGyro: same("gyroEnabled"),
    gyroActive: same("gyroEnabled"),
  },
  "us-1219881-sundback-zipper": {
    sliderPosition: same("sliderPositionPct"),
    posPct: same("sliderPositionPct"),
    position: same("sliderPositionPct"),
    sliderPos: same("sliderPositionPct"),
    pullForce: same("pullForceN"),
    pull: same("pullForceN"),
    pullN: same("pullForceN"),
    lateralTension: same("lateralTensionN"),
    tension: same("lateralTensionN"),
    tensionN: same("lateralTensionN"),
    transverseTension: same("lateralTensionN"),
    flexAngle: same("flexAngleDeg"),
    flexDeg: same("flexAngleDeg"),
    flexion: same("flexAngleDeg"),
    bendingAngle: same("flexAngleDeg"),
    toothDensity: same("toothDensityTpi"),
    tpi: same("toothDensityTpi"),
    densityTpi: same("toothDensityTpi"),
    stagger: same("staggerAligned"),
    staggered: same("staggerAligned"),
    claim1Stagger: same("staggerAligned"),
  },
  "us-1773980-farnsworth-tv": {
    anodeKv: {
      canonical: "anodeVoltage",
      toCanonical: (kv) => kv * 1000,
      fromCanonical: (v) => v / 1000,
    },
    anodeVoltage: same("anodeVoltageKv"),
    voltageKv: same("anodeVoltageKv"),
    deflectionCoilCurrent: same("coilCurrent"),
    deflectionCurrent: same("coilCurrent"),
    deflectionCurrentA: same("coilCurrent"),
    lightIntensity: same("lightIntensityLux"),
    lux: same("lightIntensityLux"),
    hFreq: same("horizontalFreqKhz"),
    horizontalFreq: same("horizontalFreqKhz"),
    lineFreqKhz: same("horizontalFreqKhz"),
    hScanFreq: same("horizontalFreqKhz"),
    vFreq: same("verticalFreqHz"),
    verticalFreq: same("verticalFreqHz"),
    frameFreqHz: same("verticalFreqHz"),
    vScanFreq: same("verticalFreqHz"),
    lines: same("scanLines"),
    rasterLines: same("scanLines"),
    numLines: same("scanLines"),
  },
  "us-879532-de-forest-audion": {
    gridVoltage: same("gridBiasVoltageV"),
    gridVoltageV: same("gridBiasVoltageV"),
    gridBiasV: same("gridBiasVoltageV"),
    plateVoltage: same("plateVoltageV"),
    filamentCurrent: same("filamentCurrentA"),
    rfInputMv: same("gridSignalAmplitudeMv"),
    rfInput: same("gridSignalAmplitudeMv"),
    signalAmplitude: same("gridSignalAmplitudeMv"),
    signalAmplitudeMv: same("gridSignalAmplitudeMv"),
    inputSignalMv: same("gridSignalAmplitudeMv"),
    gridSignalMv: same("gridSignalAmplitudeMv"),
    loadResistance: same("loadResistanceKOhms"),
    loadResistanceKohm: same("loadResistanceKOhms"),
  },
  "us-2318259-sikorsky-helicopter": {
    collective: same("collectivePitchDeg"),
    collectivePitch: same("collectivePitchDeg"),
    pitchDeg: same("collectivePitchDeg"),
    cyclicPitch: same("cyclicPitchForwardDeg"),
    cyclicPitchDeg: same("cyclicPitchForwardDeg"),
    cyclicRoll: same("cyclicRollRightDeg"),
    cyclicRollDeg: same("cyclicRollRightDeg"),
    pedal: same("tailRotorPedalPercent"),
    pedals: same("tailRotorPedalPercent"),
    tailPedal: same("tailRotorPedalPercent"),
    rudderPedals: same("tailRotorPedalPercent"),
    pedalPercent: same("tailRotorPedalPercent"),
    throttle: same("engineThrottlePercent"),
    throttlePercent: same("engineThrottlePercent"),
    engineThrottle: same("engineThrottlePercent"),
    running: same("engineRunning"),
    engine: same("engineRunning"),
    ignition: same("engineRunning"),
  },
  "gb-931-arkwright-water-frame": {
    rpm: same("waterWheelRpm"),
    wheelRpm: same("waterWheelRpm"),
    speedRpm: same("waterWheelRpm"),
    wheelSpeed: same("waterWheelRpm"),
    draftRatio: same("totalDraftRatio"),
    draft: same("totalDraftRatio"),
    draftD: same("totalDraftRatio"),
    clampingWeightKg: same("rollerClampingWeightKg"),
    clampingWeight: same("rollerClampingWeightKg"),
    weightKg: same("rollerClampingWeightKg"),
    rollerWeight: same("rollerClampingWeightKg"),
    stapleLength: same("stapleLengthMm"),
    fiberLength: same("stapleLengthMm"),
    staple: same("stapleLengthMm"),
    rovingCountNe: same("inputRovingCountNe"),
    rovingCount: same("inputRovingCountNe"),
    inputRoving: same("inputRovingCountNe"),
  },
  "gb-1306-watt-rotary-engine": {
    spm: same("strokeRateSpm"),
    strokeRate: same("strokeRateSpm"),
    speedSpm: same("strokeRateSpm"),
    beamSpm: same("strokeRateSpm"),
    boilerPressure: same("boilerPressureKpa"),
    pressureKpa: same("boilerPressureKpa"),
    steamPressure: same("boilerPressureKpa"),
    pressure: same("boilerPressureKpa"),
    gearRatio: same("gearRatioNpOverNs"),
    ratio: same("gearRatioNpOverNs"),
    toothRatio: same("gearRatioNpOverNs"),
    gearRatioNpNs: same("gearRatioNpOverNs"),
    flywheelMass: same("flywheelMassKg"),
    massKg: same("flywheelMassKg"),
    flywheelWeight: same("flywheelMassKg"),
  },
  "gb-1420-cort-puddling-rolling": {
    furnaceTemp: same("furnaceTemperatureCelsius"),
    temperatureCelsius: same("furnaceTemperatureCelsius"),
    temperatureC: same("furnaceTemperatureCelsius"),
    tempC: same("furnaceTemperatureCelsius"),
    furnaceTemperature: same("furnaceTemperatureCelsius"),
    initialCarbon: same("initialCarbonPercent"),
    carbonPercent: same("initialCarbonPercent"),
    pigIronCarbon: same("initialCarbonPercent"),
    c0: same("initialCarbonPercent"),
    rabbleRpm: same("rabbleStirringRpm"),
    stirringRpm: same("rabbleStirringRpm"),
    rabbleSpeed: same("rabbleStirringRpm"),
    puddlingTime: same("puddlingDurationMinutes"),
    durationMinutes: same("puddlingDurationMinutes"),
    puddleDuration: same("puddlingDurationMinutes"),
    timeMinutes: same("puddlingDurationMinutes"),
    rollerPasses: same("rollerPassCount"),
    passes: same("rollerPassCount"),
    passCount: same("rollerPassCount"),
  },
  "us-x1-hopkins-potash": {
    roastTemp: same("roastTempC"),
    tempC: same("roastTempC"),
    furnaceTemp: same("roastTempC"),
    furnaceTempC: same("roastTempC"),
    roastTemperature: same("roastTempC"),
    temperatureC: same("roastTempC"),
    roastingTime: same("roastTimeHours"),
    timeHours: same("roastTimeHours"),
    roastTime: same("roastTimeHours"),
    roastHours: same("roastTimeHours"),
    durationHours: same("roastTimeHours"),
    batchKg: same("ashBatchKg"),
    ashBatch: same("ashBatchKg"),
    ashMass: same("ashBatchKg"),
    rawAshKg: same("ashBatchKg"),
    waterTemp: same("waterTempC"),
    leachTempC: same("waterTempC"),
    leachWaterTemp: same("waterTempC"),
    leachWaterTempC: same("waterTempC"),
    waterTemperature: same("waterTempC"),
  },
  "us-2543181-land-polaroid": {
    devTimeSec: same("developmentTimeSec"),
    developmentTime: same("developmentTimeSec"),
    devTime: same("developmentTimeSec"),
    time: same("developmentTimeSec"),
    processingTime: same("developmentTimeSec"),
    exposure: same("exposureFraction"),
    exposureLevel: same("exposureFraction"),
    expFraction: same("exposureFraction"),
    viscosity: same("reagentViscosityCp"),
    viscosityCp: same("reagentViscosityCp"),
    gelViscosity: same("reagentViscosityCp"),
    rollerGap: same("rollerGapUm"),
    gap: same("rollerGapUm"),
    gapUm: same("rollerGapUm"),
    spreadGap: same("rollerGapUm"),
    ph: same("alkaliPh"),
    developerPh: same("alkaliPh"),
    developerAlkaliPh: same("alkaliPh"),
    claim1: same("claim1Active"),
    claim1Pod: same("claim1Active"),
    podPresent: same("claim1Active"),
    reagentPod: same("claim1Active"),
  },
  "us-2717437-mestral-velcro": {
    diameter: same("filamentDiameterMm"),
    filamentDiameter: same("filamentDiameterMm"),
    diameterMm: same("filamentDiameterMm"),
    length: same("hookLengthMm"),
    hookHeight: same("hookLengthMm"),
    hookLength: same("hookLengthMm"),
    heightMm: same("hookLengthMm"),
    density: same("hookDensityPerCm2"),
    pileDensity: same("hookDensityPerCm2"),
    hookDensity: same("hookDensityPerCm2"),
    densityPerCm2: same("hookDensityPerCm2"),
    peelAngle: same("peelAngleDeg"),
    angle: same("peelAngleDeg"),
    clampAngle: same("peelAngleDeg"),
    angleDeg: same("peelAngleDeg"),
    progress: same("peelProgress"),
    peelFront: same("peelProgress"),
    advance: same("peelProgress"),
    peelAdvance: same("peelProgress"),
  },
  "us-2846084-goertz-electronic-master-slave-manipulator": {
    hPivot: same("horizontalArmPivot"),
    armPivot: same("horizontalArmPivot"),
    horizontalPivot: same("horizontalArmPivot"),
    axis113b: same("horizontalArmPivot"),
    hRoll: same("horizontalArmRoll"),
    armRoll: same("horizontalArmRoll"),
    horizontalRoll: same("horizontalArmRoll"),
    vPivot: same("verticalArmPivot"),
    vertPivot: same("verticalArmPivot"),
    verticalPivot: same("verticalArmPivot"),
    axis126: same("verticalArmPivot"),
    vRoll: same("verticalArmRoll"),
    vertRoll: same("verticalArmRoll"),
    verticalRoll: same("verticalArmRoll"),
    axis171: same("toolAxis171"),
    toolPivot171: same("toolAxis171"),
    wrist171: same("toolAxis171"),
    pitch171: same("toolAxis171"),
    axis172: same("toolAxis172"),
    toolPivot172: same("toolAxis172"),
    wrist172: same("toolAxis172"),
    yaw172: same("toolAxis172"),
    gripper: same("gripperClosure"),
    closure: same("gripperClosure"),
    grip: same("gripperClosure"),
    jawClosure: same("gripperClosure"),
    toolClosure: same("gripperClosure"),
    contact: same("contactResistance"),
    resistance: same("contactResistance"),
    obstruction: same("contactResistance"),
    gripperObstruction: same("contactResistance"),
    forceReflection: same("forceReflectionEnabled"),
    reflection: same("forceReflectionEnabled"),
    forceFeedback: same("forceReflectionEnabled"),
    claim9: same("forceReflectionEnabled"),
    tachometerDamping: same("tachometerDampingEnabled"),
    tachometer: same("tachometerDampingEnabled"),
    damping: same("tachometerDampingEnabled"),
    rateFeedback: same("tachometerDampingEnabled"),
    claim11: same("tachometerDampingEnabled"),
    limiter: same("limiterEnabled"),
    saturationLimiter: same("limiterEnabled"),
    claim10: same("limiterEnabled"),
    claim12: same("limiterEnabled"),
  },
  "us-2929922-townes-laser": {
    cavityLength: same("cavityLengthCm"),
    lengthCm: same("cavityLengthCm"),
    chamberLengthCm: same("cavityLengthCm"),
    length: same("cavityLengthCm"),
    chamberLength: same("cavityLengthCm"),
    chamberDiameter: same("chamberDiameterCm"),
    diameterCm: same("chamberDiameterCm"),
    diameter: same("chamberDiameterCm"),
    tubeDiameterCm: same("chamberDiameterCm"),
    boreDiameterCm: same("chamberDiameterCm"),
    endReflectivity: same("endReflectivityPct"),
    reflectivityPct: same("endReflectivityPct"),
    reflectivity: same("endReflectivityPct"),
    mirrorReflectivityPct: same("endReflectivityPct"),
    endMirrorReflectivity: same("endReflectivityPct"),
    pumpExcitation: same("pumpExcitationPct"),
    excitationPct: same("pumpExcitationPct"),
    pumpPowerPct: same("pumpExcitationPct"),
    pump: same("pumpExcitationPct"),
    excitation: same("pumpExcitationPct"),
    modeAperture: same("modeApertureOpenPct"),
    apertureOpenPct: same("modeApertureOpenPct"),
    aperturePct: same("modeApertureOpenPct"),
    aperture: same("modeApertureOpenPct"),
    modeSelector: same("modeApertureOpenPct"),
    modulationField: same("modulationFieldPct"),
    zeemanFieldPct: same("modulationFieldPct"),
    zeemanField: same("modulationFieldPct"),
    modulation: same("modulationFieldPct"),
    fieldPct: same("modulationFieldPct"),
    claim1: same("claim1PathPresent"),
    claim1Path: same("claim1PathPresent"),
    communicationsPath: same("claim1PathPresent"),
    pathPresent: same("claim1PathPresent"),
  },
  "us-2988237-devol-programmed-transfer": {
    recordedCode: same("recordedSlot"),
    programSlot: same("recordedSlot"),
    programCode: same("recordedSlot"),
    recordedPosition: same("recordedSlot"),
    recorded: same("recordedSlot"),
    sensedCode: same("sensedSlot"),
    encoderSlot: same("sensedSlot"),
    encoderCode: same("sensedSlot"),
    sensedPosition: same("sensedSlot"),
    sensed: same("sensedSlot"),
    bits: same("bitWidth"),
    codeBits: same("bitWidth"),
    resolutionBits: same("bitWidth"),
    codeWidth: same("bitWidth"),
    anticipation: same("anticipationEnabled"),
    claim8: same("anticipationEnabled"),
    anticipatorySensing: same("anticipationEnabled"),
    advanceSensing: same("anticipationEnabled"),
    recordMode: same("recordingMode"),
    claim5: same("recordingMode"),
    teachMode: same("recordingMode"),
    mode: same("recordingMode"),
    gripper: same("gripperClosed"),
    claim6: same("gripperClosed"),
    gripperState: same("gripperClosed"),
    jawClosed: same("gripperClosed"),
    seizing: same("gripperClosed"),
  },
  "us-3119501-lemelson-automatic-warehousing": {
    railAddress: same("railAddressFraction"),
    carrierX: same("railAddressFraction"),
    railFraction: same("railAddressFraction"),
    xAddress: same("railAddressFraction"),
    rail: same("railAddressFraction"),
    levelAddress: same("levelAddressFraction"),
    carrierY: same("levelAddressFraction"),
    levelFraction: same("levelAddressFraction"),
    yAddress: same("levelAddressFraction"),
    verticalAddress: same("levelAddressFraction"),
    level: same("levelAddressFraction"),
    vertical: same("levelAddressFraction"),
    shuttleExtension: same("shuttleExtensionFraction"),
    shuttleZ: same("shuttleExtensionFraction"),
    extensionFraction: same("shuttleExtensionFraction"),
    zExtension: same("shuttleExtensionFraction"),
    shuttle: same("shuttleExtensionFraction"),
    extension: same("shuttleExtensionFraction"),
    autoAddressing: same("automaticAddressing"),
    presetAddressing: same("automaticAddressing"),
    claim1: same("automaticAddressing"),
    addressing: same("automaticAddressing"),
    automaticSequence: same("automaticAddressing"),
  },
  "us-3138743-kilby-integrated-circuit": {
    sectionReveal: same("sectionRevealFraction"),
    revealFraction: same("sectionRevealFraction"),
    reveal: same("sectionRevealFraction"),
    section: same("sectionRevealFraction"),
    wireArch: same("wireArchFraction"),
    archFraction: same("wireArchFraction"),
    wireHeight: same("wireArchFraction"),
    wire70Arch: same("wireArchFraction"),
    arch: same("wireArchFraction"),
    conductiveMeans: same("claim1ConductiveMeansPresent"),
    conductiveMeansPresent: same("claim1ConductiveMeansPresent"),
    claim1: same("claim1ConductiveMeansPresent"),
    claim1ConductiveMeans: same("claim1ConductiveMeansPresent"),
    interconnections: same("claim1ConductiveMeansPresent"),
  },
  "us-3212649-amf-versatran": {
    column: same("columnRotation"),
    rotation: same("columnRotation"),
    columnTurn: same("columnRotation"),
    turn: same("columnRotation"),
    lift: same("carriageLift"),
    carriage: same("carriageLift"),
    verticalLift: same("carriageLift"),
    verticalTravel: same("carriageLift"),
    reach: same("armTravel"),
    arm: same("armTravel"),
    horizontalTravel: same("armTravel"),
    horizontalReach: same("armTravel"),
    wristTurn: same("wristRotation"),
    roll: same("wristRotation"),
    armAxisRotation: same("wristRotation"),
    swing: same("wristSwing"),
    yaw: same("wristSwing"),
    wristAngle: same("wristSwing"),
    gripper: same("gripperOperation"),
    jaw: same("gripperOperation"),
    grip: same("gripperOperation"),
    jawClosure: same("gripperOperation"),
    mode: same("teachReplayMode"),
    replayMode: same("teachReplayMode"),
    teachMode: same("teachReplayMode"),
    playbackMode: same("teachReplayMode"),
    recordReplay: same("teachReplayMode"),
    phaseOffset: same("resolverPhaseOffset"),
    offset: same("resolverPhaseOffset"),
    resolverOffset: same("resolverPhaseOffset"),
    phaseError: same("resolverPhaseOffset"),
    claim1: same("claim1TopologyEnabled"),
    claim1Topology: same("claim1TopologyEnabled"),
    sixMotionTopology: same("claim1TopologyEnabled"),
    topologyEnabled: same("claim1TopologyEnabled"),
    claim8: same("claim8RecordPlaybackEnabled"),
    claim8Playback: same("claim8RecordPlaybackEnabled"),
    recordPlaybackEnabled: same("claim8RecordPlaybackEnabled"),
    recordPlayback: same("claim8RecordPlaybackEnabled"),
    claim12: same("claim12PinionGripperEnabled"),
    claim12Gripper: same("claim12PinionGripperEnabled"),
    pinionGripperEnabled: same("claim12PinionGripperEnabled"),
    pinionGripper: same("claim12PinionGripperEnabled"),
  },
  "us-3260375-lemelson-adjustable-manipulator": {
    carriage: same("carriagePosition"),
    carriageX: same("carriagePosition"),
    xPosition: same("carriagePosition"),
    positionX: same("carriagePosition"),
    elevation: same("columnElevation"),
    columnZ: same("columnElevation"),
    lift: same("columnElevation"),
    hoist: same("columnElevation"),
    azimuth: same("columnAzimuth"),
    turntable: same("columnAzimuth"),
    turntableAngle: same("columnAzimuth"),
    rotation: same("columnAzimuth"),
    pivot: same("wristPivot"),
    wrist: same("wristPivot"),
    wristAngle: same("wristPivot"),
    bevelPivot: same("wristPivot"),
    gripper: same("jawClosure"),
    jaw: same("jawClosure"),
    grip: same("jawClosure"),
    closure: same("jawClosure"),
    phase: same("cyclePhase"),
    stage: same("cyclePhase"),
    sequencePhase: same("cyclePhase"),
    step: same("cyclePhase"),
    stop1Rotary: same("stop1Azimuth"),
    azimuthLimit1: same("stop1Azimuth"),
    stop1Angle: same("stop1Azimuth"),
    stop2Rotary: same("stop2Azimuth"),
    azimuthLimit2: same("stop2Azimuth"),
    stop2Angle: same("stop2Azimuth"),
    stop1Vertical: same("stop1Elevation"),
    verticalLimit1: same("stop1Elevation"),
    stop1Height: same("stop1Elevation"),
    stop2Vertical: same("stop2Elevation"),
    verticalLimit2: same("stop2Elevation"),
    stop2Height: same("stop2Elevation"),
  },
  "us-3313014-lemelson-automatic-production": {
    carrierAddress: same("carrierAddressFraction"),
    carrierX: same("carrierAddressFraction"),
    addressFraction: same("carrierAddressFraction"),
    address: same("carrierAddressFraction"),
    lift: same("liftFraction"),
    verticalLift: same("liftFraction"),
    liftPose: same("liftFraction"),
    mzLift: same("liftFraction"),
    reach: same("reachFraction"),
    platformReach: same("reachFraction"),
    myReach: same("reachFraction"),
    extension: same("reachFraction"),
    marker: same("stationDetected"),
    markerDetected: same("stationDetected"),
    markerSensed: same("stationDetected"),
    stationSensed: same("stationDetected"),
    coupled: same("stationCoupled"),
    contactsCoupled: same("stationCoupled"),
    stationContact: same("stationCoupled"),
    claim7: same("stationCoupled"),
    progress: same("cycleProgress"),
    cycle: same("cycleProgress"),
    sequenceProgress: same("cycleProgress"),
    cycleFraction: same("cycleProgress"),
  },
  "us-3353115-maiman-ruby-laser": {
    pumpPowerWatts: same("pumpEnergyJoules"),
    pumpPower: same("pumpEnergyJoules"),
    pumpEnergy: same("pumpEnergyJoules"),
    flashEnergy: same("pumpEnergyJoules"),
    flashDuration: same("flashDurationMs"),
    flashMs: same("flashDurationMs"),
    pulseDurationMs: same("flashDurationMs"),
    pulseDuration: same("flashDurationMs"),
    flashTimeMs: same("flashDurationMs"),
    durationMs: same("flashDurationMs"),
    rodLength: same("rodLengthCm"),
    crystalLengthCm: same("rodLengthCm"),
    laserRodLength: same("rodLengthCm"),
    outputReflectivity: same("outputMirrorReflectivity"),
    mirrorReflectivity: same("outputMirrorReflectivity"),
    r2: same("outputMirrorReflectivity"),
    couplerReflectivity: same("outputMirrorReflectivity"),
    crystalTemperature: same("crystalTemperatureKelvin"),
    temperatureK: same("crystalTemperatureKelvin"),
    temperature: same("crystalTemperatureKelvin"),
    tempK: same("crystalTemperatureKelvin"),
  },
  "us-3728480-baer-odyssey": {
    p1X: same("player1PotX"),
    p1PotX: same("player1PotX"),
    dot1X: same("player1PotX"),
    knob17: same("player1PotX"),
    player1X: same("player1PotX"),
    p1Y: same("player1PotY"),
    p1PotY: same("player1PotY"),
    dot1Y: same("player1PotY"),
    knob16: same("player1PotY"),
    player1Y: same("player1PotY"),
    p2X: same("player2PotX"),
    p2PotX: same("player2PotX"),
    dot2X: same("player2PotX"),
    knob17Sub1: same("player2PotX"),
    player2X: same("player2PotX"),
    p2Y: same("player2PotY"),
    p2PotY: same("player2PotY"),
    dot2Y: same("player2PotY"),
    knob16Sub1: same("player2PotY"),
    player2Y: same("player2PotY"),
    english: same("englishControl"),
    spin: same("englishControl"),
    spinPot: same("englishControl"),
    englishSpin: same("englishControl"),
    ballSpeed: same("ballSpeedMultiplier"),
    speedMultiplier: same("ballSpeedMultiplier"),
    speed: same("ballSpeedMultiplier"),
    channel: same("rfChannel"),
    vhfChannel: same("rfChannel"),
    ch: same("rfChannel"),
    chromaPhase: same("chromaPhaseDeg"),
    chroma: same("chromaPhaseDeg"),
    huePhase: same("chromaPhaseDeg"),
    colorPhase: same("chromaPhaseDeg"),
  },
  "us-3858581-kamen-medication-injection-device": {
    pulseCount: same("selectedPulseCount"),
    pulses: same("selectedPulseCount"),
    turnsCount: same("selectedPulseCount"),
    selectedPulses: same("selectedPulseCount"),
    displaySpeed: same("displayTurnsPerSecond"),
    turnsPerSecond: same("displayTurnsPerSecond"),
    motorSpeed: same("displayTurnsPerSecond"),
    speed: same("displayTurnsPerSecond"),
    offInterval: same("offIntervalDisplaySeconds"),
    pauseInterval: same("offIntervalDisplaySeconds"),
    motorOffSeconds: same("offIntervalDisplaySeconds"),
    offSeconds: same("offIntervalDisplaySeconds"),
    clutch: same("clutchEngaged"),
    clutchCoupled: same("clutchEngaged"),
    claim3Clutch: same("clutchEngaged"),
    run: same("running"),
    active: same("running"),
    motorRunning: same("running"),
  },
  "us-4063220-metcalfe-ethernet": {
    cableLength: same("cableLengthMeters"),
    length: same("cableLengthMeters"),
    coaxLength: same("cableLengthMeters"),
    busLength: same("cableLengthMeters"),
    dataRate: same("dataRateMbps"),
    bitRate: same("dataRateMbps"),
    transmissionRate: same("dataRateMbps"),
    stations: same("stationCount"),
    nodes: same("stationCount"),
    contenderCount: same("stationCount"),
    load: same("offeredLoad"),
    trafficLoad: same("offeredLoad"),
    g: same("offeredLoad"),
    packetSize: same("packetSizeBytes"),
    frameSize: same("packetSizeBytes"),
    packetBytes: same("packetSizeBytes"),
    collision: same("triggerCollision"),
    forceCollision: same("triggerCollision"),
  },
  "us-4068536-stackhouse-manipulator": {
    forearmRoll: same("forearmRollDeg"),
    theta1: same("forearmRollDeg"),
    roll1: same("forearmRollDeg"),
    intermediateRoll: same("intermediateRollDeg"),
    theta2: same("intermediateRollDeg"),
    roll2: same("intermediateRollDeg"),
    toolRoll: same("toolRollDeg"),
    theta3: same("toolRollDeg"),
    roll3: same("toolRollDeg"),
    firstOblique: same("firstObliqueAngleDeg"),
    alphaAB: same("firstObliqueAngleDeg"),
    alpha1: same("firstObliqueAngleDeg"),
    secondOblique: same("secondObliqueAngleDeg"),
    alphaBC: same("secondObliqueAngleDeg"),
    alpha2: same("secondObliqueAngleDeg"),
    pointP: same("singleIntersection"),
    exactIntersection: same("singleIntersection"),
    preferredPointP: same("singleIntersection"),
  },
  "us-4098001-watson-rcc": {
    lateralContact: same("lateralContactFraction"),
    contactFraction: same("lateralContactFraction"),
    contact: same("lateralContactFraction"),
    axisMismatch: same("axisMismatchFraction"),
    mismatchFraction: same("axisMismatchFraction"),
    mismatch: same("axisMismatchFraction"),
    remoteCenter: same("remoteCenterTopology"),
    claim1Topology: same("remoteCenterTopology"),
    topology: same("remoteCenterTopology"),
    antiTwist: same("antiTwistConstraint"),
    claim2Constraint: same("antiTwistConstraint"),
    torqueConstraint: same("antiTwistConstraint"),
  },
  "us-4341502-makino-scara": {
    firstLinkAngle: same("firstLinkAngleDeg"),
    theta1: same("firstLinkAngleDeg"),
    link1Angle: same("firstLinkAngleDeg"),
    fourthLinkAngle: same("fourthLinkAngleDeg"),
    theta2: same("fourthLinkAngleDeg"),
    theta4: same("fourthLinkAngleDeg"),
    link4Angle: same("fourthLinkAngleDeg"),
    toolAttitude: same("toolAttitudeDeg"),
    phi: same("toolAttitudeDeg"),
    attitude: same("toolAttitudeDeg"),
    topology: same("topologyVariant"),
    claimTopology: same("topologyVariant"),
    variant: same("topologyVariant"),
    claim: same("topologyVariant"),
  },
  "us-5121329-crump-fdm": {
    nozzleTemp: same("nozzleTempC"),
    tempC: same("nozzleTempC"),
    temperature: same("nozzleTempC"),
    printSpeed: same("printSpeedMmS"),
    speedMmS: same("printSpeedMmS"),
    feedSpeed: same("printSpeedMmS"),
    layerHeight: same("layerHeightMm"),
    sliceHeight: same("layerHeightMm"),
    heightMm: same("layerHeightMm"),
    roadWidth: same("roadWidthMm"),
    beadWidth: same("roadWidthMm"),
    extrusionWidth: same("roadWidthMm"),
    widthMm: same("roadWidthMm"),
  },
  "us-6302230-kamen-segway": {
    pitch: same("riderPitchDeg"),
    lean: same("riderPitchDeg"),
    steering: same("steeringInput"),
    yaw: same("steeringInput"),
    mass: same("riderMassKg"),
    riderMass: same("riderMassKg"),
    friction: same("groundFrictionCoeff"),
    speedLimit: same("speedLimitMS"),
  },
  "us-6594844-roomba": {
    speed: same("wheelSpeedMps"),
    driveSpeed: same("wheelSpeedMps"),
    turnRate: same("turnRateRadSec"),
    deflectionRate: same("turnRateRadSec"),
    opticalSensor: same("opticalSensorEnabled"),
    optical: same("opticalSensorEnabled"),
    claim1Optical: same("opticalSensorEnabled"),
  },
  "us-7479949-multitouch": {
    separation: same("fingerSeparationMm"),
    separationMm: same("fingerSeparationMm"),
    fingerSeparation: same("fingerSeparationMm"),
    count: same("fingerCount"),
    fingers: same("fingerCount"),
    initialMotionAngle: same("initialMotionAngleDeg"),
    motionAngle: same("initialMotionAngleDeg"),
    angleDeg: same("initialMotionAngleDeg"),
    angle: same("initialMotionAngleDeg"),
  },
  "us-4921293-salisbury-robot-hand": {
    t1: same("tensionT1N"),
    tension1: same("tensionT1N"),
    T1: same("tensionT1N"),
    t2: same("tensionT2N"),
    tension2: same("tensionT2N"),
    T2: same("tensionT2N"),
    t3: same("tensionT3N"),
    tension3: same("tensionT3N"),
    T3: same("tensionT3N"),
    t4: same("tensionT4N"),
    tension4: same("tensionT4N"),
    T4: same("tensionT4N"),
    radiusScale: same("radiusScaleMm"),
    rScale: same("radiusScaleMm"),
    r2Scale: same("radiusScaleMm"),
    idlerFixed: same("firstIdlerFixed"),
    claim2Idler: same("firstIdlerFixed"),
  },
  "us-4976582-clavel-delta-robot": {
    arm1: same("armOneInput"),
    arm1Input: same("armOneInput"),
    input1: same("armOneInput"),
    arm2: same("armTwoInput"),
    arm2Input: same("armTwoInput"),
    input2: same("armTwoInput"),
    arm3: same("armThreeInput"),
    arm3Input: same("armThreeInput"),
    input3: same("armThreeInput"),
    toolAxis: same("toolAxisInput"),
    toolInput: same("toolAxisInput"),
    axis10: same("toolAxisInput"),
    claim1: same("claim1TopologyEnabled"),
    topologyEnabled: same("claim1TopologyEnabled"),
    claim2: same("claim2PairedBarsEnabled"),
    pairedBarsEnabled: same("claim2PairedBarsEnabled"),
    claim8: same("claim8BaseMotorEnabled"),
    baseMotorEnabled: same("claim8BaseMotorEnabled"),
    toolMotorEnabled: same("claim8BaseMotorEnabled"),
  },
};

export function canonicalizeParam(
  patentId: string,
  paramId: string,
  value: number,
): { id: string; value: number } {
  const spec = PATENT_PARAM_ALIASES[patentId]?.[paramId];
  if (!spec) return { id: paramId, value };
  return {
    id: spec.canonical,
    value: spec.toCanonical ? spec.toCanonical(value) : value,
  };
}

export function expandParamAliases(
  patentId: string,
  params: Record<string, number>,
): Record<string, number> {
  const aliases = PATENT_PARAM_ALIASES[patentId];
  if (!aliases) return params;
  const out = { ...params };
  for (const [alias, spec] of Object.entries(aliases)) {
    const canon = out[spec.canonical];
    if (typeof canon === "number") {
      out[alias] = spec.fromCanonical ? spec.fromCanonical(canon) : canon;
    }
  }
  return out;
}
