import type {
  CuratedSpecificationEdition,
  CuratedSpecificationInline,
  CuratedSpecificationInlines,
} from "@/types/patent";

const term = (
  surfaceText: string,
  key: string,
  definition: string,
): CuratedSpecificationInline => ({
  kind: "term",
  text: surfaceText,
  label: key,
  definition,
});

export const DIESEL_FIGURE_DIMS: Record<number, { width: number; height: number }> = {
  1: { width: 600, height: 470 },
  2: { width: 430, height: 600 },
  3: { width: 520, height: 620 },
};

function figureAssetPath(number: number): string {
  return `/patents/figures/us-542846-diesel-engine/fig-${number}-source-crop-v1.png`;
}

function makePreview(
  surfaceText: string,
  figureNumbers: number[],
  altText: string,
): CuratedSpecificationInline {
  return {
    kind: "reference",
    text: surfaceText,
    href: `#figure-${figureNumbers[0]}`,
    referenceType: "figure",
    label: altText,
    figurePreviews: figureNumbers.map((num) => ({
      src: figureAssetPath(num),
      alt: `Figure ${num}: ${altText}`,
      width: DIESEL_FIGURE_DIMS[num]?.width ?? 600,
      height: DIESEL_FIGURE_DIMS[num]?.height ?? 600,
    })),
  };
}

const p = (
  ...inlines: (string | CuratedSpecificationInline)[]
): {
  kind: "paragraph";
  inlines: CuratedSpecificationInlines;
} => ({
  kind: "paragraph",
  inlines: inlines.map((item) => (typeof item === "string" ? { kind: "text", text: item } : item)),
});

export const dieselParallelReadings: Readonly<Record<number, readonly string[]>> = {
  2: [
    "To all whom it may concern: Be it known that I, Rudolf Diesel, residing at Berlin, Germany, have invented new and useful Improvements in Internal-Combustion Engines.",
  ],
  4: [
    "Fundamental Principle: Converting fuel heat into mechanical work without a spark plug by compressing air past the ignition temperature and injecting fuel gradually.",
  ],
  5: [
    "Thermodynamic Isothermal Expansion: Fuel injection rate is precisely metered so heat generated by combustion equals mechanical expansion work, preventing destructive peak temperatures.",
  ],
  7: [
    "Brief Description of Figures: FIG. 1 is a theoretical pressure-volume indicator diagram; FIG. 2 is a vertical sectional view of the engine cylinder; FIG. 3 shows the high-pressure fuel injector valve.",
  ],
  9: [
    "Detailed Description: Cylinder C houses piston P compressing pure atmospheric air during the upstroke to over 30 atmospheres (500°C), well above the spontaneous ignition threshold.",
  ],
  10: [
    "High-Pressure Fuel Injection: Liquid fuel is pulverized and admitted through nozzle D by an auxiliary air blast, igniting spontaneously upon contact with incandescent compressed air.",
  ],
  11: [
    "Governor Control: The cut-off valve timing is modulated by a centrifugal governor to regulate the duration of fuel injection according to mechanical load.",
  ],
  12: [
    "Thermal Efficiency: By eliminating external ignition timing and jacket cooling heat losses during combustion, the engine achieves unprecedented thermal efficiencies exceeding 35%.",
  ],
};

export const dieselArchivalEdition: CuratedSpecificationEdition = {
  kind: "manual-react-edition",
  sourcePdfSha256: "57679379a0e1d1dc97591e6f634fa6f7ed7c0ec3b465edf493b5f79595a0e866",
  preparedBy: "Classic Patents Editorial Team",
  preparedAt: "2026-08-20",
  completeFacsimileReviewed: true,
  blocks: [
    {
      kind: "masthead",
      lines: [
        "United States Patent Office",
        "Rudolf Diesel, of Berlin, Germany",
        "Patent No.: US 542,846",
        "Date of Patent: July 16, 1895",
        "INTERNAL-COMBUSTION ENGINE",
        "Application filed August 26, 1892. Serial No. 444,233. (No model.)",
        "Patented in Germany February 28, 1892, No. 67,207; in Spain July 1, 1892, No. 13,454; in France March 25, 1893, No. 228,879; in Belgium March 27, 1893, No. 104,013; in England April 29, 1893, No. 7,241; in Austria-Hungary July 12, 1893, No. 44,117 and No. 79,660; in Switzerland July 24, 1893, No. 6,707; in Sweden August 24, 1893, No. 5,036; in Italy January 24, 1894, No. 35,468, and in Russia April 22, 1895, No. 14,028.",
      ],
    },
    {
      kind: "heading",
      level: 2,
      text: "SPECIFICATION",
    },
    p(
      "To all whom it may concern: Be it known that I, Rudolf Diesel, a citizen of the German Empire, residing at Berlin, Germany, have invented certain new and useful Improvements in Internal-Combustion Engines, of which the following is a specification.",
    ),
    {
      kind: "heading",
      level: 2,
      text: "THEORETICAL PRINCIPLE AND THERMODYNAMICS",
    },
    p(
      "The invention relates to a process for converting the heat energy of combustible materials into mechanical work in internal-combustion engines. In all existing combustion motors, fuel is mixed with air prior to or during compression, and ignition is triggered by an electric spark, hot tube, or flame. Consequently, the compression pressure must be strictly limited to prevent premature auto-ignition, resulting in low theoretical thermal efficiency and high fuel consumption.",
    ),
    p(
      "In the present process, pure air is drawn into the working cylinder and compressed by the working piston to a pressure far exceeding customary limits (from 30 to over 100 atmospheres). The temperature attained by this adiabatic compression is substantially higher than the ignition point of the fuel to be used. Fuel is then gradually injected into this incandescent compressed air and burns spontaneously upon entry without an explosive shock.",
    ),
    {
      kind: "heading",
      level: 2,
      text: "BRIEF DESCRIPTION OF THE DRAWINGS",
    },
    p(
      "The invention is illustrated in the accompanying drawings, in which:\n",
      makePreview("FIG. 1", [1], "Pressure-Volume Thermodynamic Indicator Diagram"),
      " is a diagram illustrating the theoretical thermodynamic cycle;\n",
      makePreview("FIG. 2", [2], "Vertical Section of Diesel Combustion Engine Cylinder"),
      " is a vertical sectional view through the working cylinder; and\n",
      makePreview("FIG. 3", [3], "High-Pressure Fuel Injection Valve Detail"),
      " is an enlarged sectional view of the fuel injection and air-atomizing nozzle.",
    ),
    {
      kind: "heading",
      level: 2,
      text: "DETAILED DESCRIPTION OF THE ENGINE",
    },
    p(
      "Referring to ",
      makePreview("FIG. 2", [2], "Engine cylinder section"),
      ", cylinder C is fitted with a heavily reinforced piston P connected to the engine crankshaft. During the intake stroke, air admission valve V admits pure atmospheric air. On the subsequent compression stroke, piston P moves toward the cylinder head, compressing the air into the small clearance space S.",
    ),
    p(
      "Referring to ",
      makePreview("FIG. 3", [3], "Fuel injection nozzle"),
      ", fuel nozzle D communicates with a high-pressure fuel pump and compressed air reservoir. When injection needle N is lifted by cam linkage, finely atomized fuel is blown into the incandescent air charge in clearance space S, initiating combustion at constant or controlled pressure.",
    ),
    p(
      "The admission of fuel is continued during a predetermined portion of the expansion stroke under the control of a speed governor, after which the fuel supply is cut off and the expanding combustion gases perform work until exhaust valve E opens near bottom dead center.",
    ),
    p(
      "Because the maximum temperature of the cycle is governed by the rate of fuel admission rather than an uncontrolled explosion, cylinder wall heat losses are drastically reduced, enabling the engine to achieve thermal efficiencies exceeding those of any previously known heat engine.",
    ),
    {
      kind: "heading",
      level: 2,
      text: "CLAIMS",
    },
    {
      kind: "claim",
      number: 1,
      inlines: [
        {
          kind: "text",
          text: "The herein described process for converting the heat energy of fuel into work, consisting in first compressing air, or a mixture of air and neutral gas or vapor, to a degree producing a temperature above the igniting point of the fuel to be consumed, then gradually introducing the fuel for combustion into the compressed air while expanding against a resistance sufficiently to prevent an essential increase of temperature and pressure, then discontinuing the supply of fuel and further expanding without transfer of heat.",
        },
      ],
    },
    {
      kind: "claim",
      number: 2,
      inlines: [
        {
          kind: "text",
          text: "In an internal combustion engine, the combination with the cylinder and piston, of a valved suction inlet for air or a mixture of air and neutral gas, a valved fuel feed constructed to gradually discharge the fuel into the cylinder, and means in operative connection with the feed valve for opening the same at the commencement of the working stroke of the piston and for closing the same at a predetermined part of the stroke, substantially as described.",
        },
      ],
    },
    {
      kind: "claim",
      number: 3,
      inlines: [
        {
          kind: "text",
          text: "In an internal combustion engine of the character specified, the combination of a combustion cylinder provided with means for gradually introducing fuel therein up to the point of cut-off, a compressor for air, a reservoir connected with the latter and with the cylinder, and an expansion chamber for the exhaust gases, substantially as described. In testimony whereof I have signed my name to this specification in the presence of two subscribing witnesses. RUDOLF DIESEL. Witnesses: LUDWIG GLASER. EDUARD PEITZ.",
        },
      ],
    },
  ],
};

export const dieselEdition = dieselArchivalEdition;
