import type {
  CuratedSpecificationEdition,
  CuratedSpecificationInline,
  CuratedSpecificationInlines,
} from "@/types/patent";

const paragraph = (inlines: CuratedSpecificationInlines) => ({
  kind: "paragraph" as const,
  inlines,
});

const term = (value: string, definition: string, label?: string): CuratedSpecificationInline => ({
  kind: "term",
  text: value,
  definition,
  label,
});

const FIGURES = {
  1: {
    src: "/patents/figures/us-4575330-hull-stereolithography/fig-1-source-crop-v1.png",
    alt: "Figure 1 from US 4,575,330: elevation view of basic stereolithography apparatus with movable UV light source, container, and elevator.",
    width: 1985,
    height: 1490,
  },
  2: {
    src: "/patents/figures/us-4575330-hull-stereolithography/fig-2-source-crop-v1.png",
    alt: "Figure 2 from US 4,575,330: perspective view of a three-dimensional object being extracted from the fluid medium.",
    width: 1990,
    height: 1488,
  },
  3: {
    src: "/patents/figures/us-4575330-hull-stereolithography/fig-3-source-crop-v1.png",
    alt: "Figure 3 from US 4,575,330: schematic perspective view of a commercial computer-controlled stereolithography system with galvanometer scanning mirrors and beam sensor.",
    width: 2055,
    height: 2932,
  },
  4: {
    src: "/patents/figures/us-4575330-hull-stereolithography/fig-4-source-crop-v1.png",
    alt: "Figure 4 from US 4,575,330: elevation view of an alternative stereolithography system using bottom-exposure through a transparent container base.",
    width: 1985,
    height: 1682,
  },
  5: {
    src: "/patents/figures/us-4575330-hull-stereolithography/fig-5-source-crop-v1.png",
    alt: "Figure 5 from US 4,575,330: sectional view of the two-phase immiscible liquid interface of Figure 4.",
    width: 1990,
    height: 1287,
  },
  6: {
    src: "/patents/figures/us-4575330-hull-stereolithography/fig-6-source-crop-v1.png",
    alt: "Figure 6 from US 4,575,330: elevation view of a stereolithography system utilizing a cathode ray tube (CRT) faceplate exposure source.",
    width: 1020,
    height: 1490,
  },
  7: {
    src: "/patents/figures/us-4575330-hull-stereolithography/fig-7-source-crop-v1.png",
    alt: "Figure 7 from US 4,575,330: elevation view of a stereolithography platform with multi-axis rotational articulation.",
    width: 991,
    height: 1489,
  },
  8: {
    src: "/patents/figures/us-4575330-hull-stereolithography/fig-8-source-crop-v1.png",
    alt: "Figure 8 from US 4,575,330: elevation view of a chemical reactive jet stereolithography system.",
    width: 1975,
    height: 1489,
  },
} as const;

const figure = (
  label: string,
  numbers: readonly (keyof typeof FIGURES)[],
): CuratedSpecificationInline => ({
  kind: "reference",
  text: label,
  href: "#",
  referenceType: "figure",
  label: `Preview ${label} from US 4,575,330 source facsimile`,
  figurePreviews: numbers.map((n) => FIGURES[n]),
});

const claim = (number: number, inlines: CuratedSpecificationInlines) => ({
  kind: "claim" as const,
  number,
  inlines,
});

export const hullStereolithographyParallelReadings: Record<number, string[]> = {
  3: [
    "The patent begins by defining stereolithography: an apparatus and process for automatically generating complex solid plastic three-dimensional parts directly from computerized design models by sequentially curing thin cross-sectional fluid layers using focused synergistic radiation.",
  ],
  4: [
    "Hull outlines the severe limitations of 1980s manufacturing: producing prototype parts required weeks or months of manual mold-making, CNC machining, or casting. Prior attempts at three-dimensional photopolymer curing (such as two-beam intersecting laser systems) were slow, unstable, and could not maintain precise surface boundary definition.",
  ],
  6: [
    "The breakthrough concept of stereolithography is to build objects layer by layer from a substantially two-dimensional surface interface. A moving radiation beam (such as a focused ultraviolet laser) draws cross-sectional patterns onto a liquid photopolymer vat, polymerizing a thin solid lamina. An elevator platform then translates the solid part down by one layer thickness, allowing liquid resin to flow over the top before the next cross-section is cured and bonded to the previous layer.",
  ],
  8: [
    "Hull summarizes the preferred apparatus embodiments illustrated in the drawing sheets: top-down laser scanning with galvanometer mirrors, bottom-up exposure through transparent immiscible fluid interfaces, direct cathode ray tube exposure, and multi-axis articulated elevator positioning.",
  ],
  10: [
    "In the primary embodiment of Figure 1 and Figure 2, a container holds a bath of curable liquid photopolymer. An ultraviolet light spot scans across the resin surface in a graphic pattern generated by a computer, solidifying a cross-sectional lamina. An elevator platform beneath the surface supports the growing part and indexes downward after each layer is polymerized.",
  ],
  11: [
    "The photopolymer resin must satisfy precise optical and physical criteria: (A) it must polymerize rapidly upon exposure to ultraviolet light; (B) it must remain non-reactive and stable across unexposed areas; (C) its viscosity must be low enough to allow fresh liquid to flow smoothly across previously solidified layers; and (D) its optical absorption must prevent excessive depth-of-cure penetration into underlying layers.",
  ],
  12: [
    "In the commercial system of Figure 3, computer CAD data is mathematically sliced into cross-sectional contour vectors. Dual high-speed orthogonal galvanometer scanning mirrors deflect a focused UV laser beam across the liquid surface with high positioning speed and sub-millimeter precision, while optical sensors monitor laser intensity and surface level.",
  ],
  13: [
    "Figures 4 and 5 illustrate an alternative bottom-exposure stereolithography system where synergistic radiation enters through a transparent container base. An immiscible, chemically inert heavy liquid (such as heavy water or fluorocarbon fluid) forms an optical separation boundary that prevents the cured polymer from adhering to the container window.",
  ],
  14: [
    "The descriptive specification concludes by noting that stereolithography provides an automated bridge between computer-aided design (CAD) and physical component manufacturing, replacing weeks of manual machining with direct additive fabrication in hours. What follows are the formal patent claims.",
  ],
};

export const hullStereolithographyArchivalEdition: CuratedSpecificationEdition = {
  kind: "manual-react-edition",
  sourcePdfSha256: "5dc2211b18f88883ee92394917154d57d102b73c26a4744332cbf0d89b1db1c7",
  preparedBy: "Classic Patents editorial agent (Gemini 3.7 Flash)",
  preparedAt: "2026-09-01",
  completeFacsimileReviewed: true,
  blocks: [
    {
      kind: "masthead",
      lines: [
        "United States Patent [19]",
        "Hull",
        "[11] Patent Number: 4,575,330",
        "[45] Date of Patent: Mar. 11, 1986",
        "APPARATUS FOR PRODUCTION OF THREE-DIMENSIONAL OBJECTS BY STEREOLITHOGRAPHY",
        "Inventor: Charles W. Hull, Arcadia, Calif.",
        "Assignee: UVP, Inc., San Gabriel, Calif.",
        "Appl. No.: 638,905",
        "Filed: Aug. 8, 1984",
      ],
    },
    {
      kind: "figure-sheet",
      figureLabel: "SHEETS 1–4 OF 4",
      title: "Stereolithography Apparatus, Laser Scanning Systems, and Immiscible Fluid Interfaces",
      description: [
        {
          text: "4,575,330. Hull. Apparatus for Production of Three-Dimensional Objects by Stereolithography. Application Filed Aug. 8, 1984. Patented Mar. 11, 1986. ",
          kind: "text",
        },
        figure("FIG. 1", [1]),
        { kind: "text", text: ", " },
        figure("FIG. 2", [2]),
        { kind: "text", text: ", " },
        figure("FIG. 3", [3]),
        { kind: "text", text: ", " },
        figure("FIG. 4", [4]),
        { kind: "text", text: ", " },
        figure("FIG. 5", [5]),
        { kind: "text", text: ", " },
        figure("FIG. 6", [6]),
        { kind: "text", text: ", " },
        figure("FIG. 7", [7]),
        { kind: "text", text: ", " },
        figure("FIG. 8", [8]),
      ],
    },
    {
      kind: "heading",
      level: 2,
      text: "BACKGROUND OF THE INVENTION",
    },
    paragraph([
      {
        kind: "text",
        text: "This invention relates generally to improvements in methods and apparatus for forming three-dimensional objects from a fluid medium and, more particularly, to a new and improved system for ",
      },
      term(
        "stereolithography",
        "The process of creating solid three-dimensional plastic parts by sequentially printing thin laminar cross-sections using actinic radiation to cure liquid photopolymers.",
      ),
      {
        kind: "text",
        text: " involving the application of synergistic stimulation, such as ultraviolet light, to a fluid medium to successively solidify thin cross-sectional laminae of the object, each lamina being integrated with the previous lamina to build up the desired three-dimensional object in a step-wise laminar fashion.",
      },
    ]),
    paragraph([
      {
        kind: "text",
        text: "It is common practice in the production of more desirable products to design, build and test various prototypes before finalizing manufacturing specifications. However, the production of such prototypes has traditionally been extremely slow, tedious and expensive, requiring skilled craftsmen to machine, cast or fabricate models by hand over weeks or months. Prior attempts to generate solid objects from photopolymer resins (such as Swainson U.S. Pat. Nos. 4,041,476 and 4,238,840) required the simultaneous intersection of two laser beams deep within a transparent body, suffering from severe positioning instability, long exposure times, and poor spatial resolution.",
      },
    ]),
    {
      kind: "heading",
      level: 2,
      text: "SUMMARY OF THE INVENTION",
    },
    paragraph([
      {
        kind: "text",
        text: "The present invention satisfies a long existing need in the art for a CAD/CAM system capable of rapidly, reliably, accurately and economically designing and fabricating three-dimensional plastic parts directly from computer memory. A container holds a fluid medium capable of altering its physical state upon exposure to ",
      },
      term(
        "synergistic stimulation",
        "Actinic energy—such as focused ultraviolet laser radiation, electron beams, or chemical agents—that initiates cross-linking and phase change from liquid to solid.",
      ),
      {
        kind: "text",
        text: ". A movable radiation source traces cross-sectional patterns across a designated working surface of the fluid medium, forming a thin solid ",
      },
      term(
        "lamina",
        "A single thin solid layer representing a two-dimensional cross-sectional slice of the three-dimensional computer model.",
      ),
      {
        kind: "text",
        text: ". An elevating platform moves the object away from the working surface, allowing fresh liquid medium to coat the previously formed layer before the next cross-section is irradiated, integrating successive laminae into a monolithic three-dimensional part.",
      },
    ]),
    {
      kind: "heading",
      level: 2,
      text: "BRIEF DESCRIPTION OF THE DRAWINGS",
    },
    paragraph([
      figure("FIG. 1", [1]),
      {
        kind: "text",
        text: " is an elevation view of a basic stereolithography apparatus; ",
      },
      figure("FIG. 2", [2]),
      {
        kind: "text",
        text: " is a perspective view showing a three-dimensional object being extracted from the fluid medium; ",
      },
      figure("FIG. 3", [3]),
      {
        kind: "text",
        text: " is a schematic perspective view of a commercial computer-controlled stereolithography system with dual galvanometer scanners; ",
      },
      figure("FIG. 4", [4]),
      {
        kind: "text",
        text: " and ",
      },
      figure("FIG. 5", [5]),
      {
        kind: "text",
        text: " illustrate an alternative bottom-exposure configuration through an immiscible fluid interface; and ",
      },
      figure("FIG. 6", [6]),
      { kind: "text", text: ", " },
      figure("FIG. 7", [7]),
      { kind: "text", text: ", and " },
      figure("FIG. 8", [8]),
      {
        kind: "text",
        text: " illustrate alternative radiation sources and multi-axis platform mechanisms.",
      },
    ]),
    {
      kind: "heading",
      level: 2,
      text: "DETAILED DESCRIPTION OF THE PREFERRED EMBODIMENTS",
    },
    paragraph([
      {
        kind: "text",
        text: "Referring to ",
      },
      figure("FIG. 1", [1]),
      {
        kind: "text",
        text: " and ",
      },
      figure("FIG. 2", [2]),
      {
        kind: "text",
        text: ", a container 21 holds a body of curable liquid photopolymer 22 having an upper working surface 23. An elevator platform 29 supported by shaft 30 is positioned just below the surface 23. A spot of ultraviolet light 27 generated by source 26 is moved across the surface by an X-Y scanning mechanism, solidifying a cross-sectional lamina 32 corresponding to the first slice of the object 30. Elevator 29 then moves down by a predetermined layer thickness (typically 0.005 to 0.020 inches), fresh liquid resin flows over the cured layer, and the next slice is drawn, bonding firmly to the underlying lamina.",
      },
    ]),
    paragraph([
      {
        kind: "text",
        text: "The curable liquid 22 must satisfy four primary criteria: (A) it must polymerize rapidly upon exposure to ultraviolet light; (B) it must remain stable and fluid in unexposed areas; (C) its viscosity must be low enough to flow quickly across the part when the elevator steps down; and (D) its optical absorption must limit the ",
      },
      term(
        "curing depth",
        "The penetration depth of actinic radiation governing layer thickness and interlaminar bonding according to the Beer-Lambert absorption law.",
      ),
      {
        kind: "text",
        text: " to ensure precise z-axis resolution without curing uncontrolled material below the target lamina.",
      },
    ]),
    paragraph([
      {
        kind: "text",
        text: "Referring to ",
      },
      figure("FIG. 3", [3]),
      {
        kind: "text",
        text: ", the commercial stereolithography system includes a helium-cadmium UV laser 26 emitting beam 27 through shutter 27a and beam expander 27b. High-speed X-Y ",
      },
      term(
        "galvanometer mirrors",
        "Precision motor-driven optical mirrors that deflect the focused UV laser spot across the photopolymer resin surface at velocities up to several meters per second.",
      ),
      {
        kind: "text",
        text: " 24 and 25 direct the beam across the vat surface 23 under control of computer 28. Sensor 28b monitors laser spot intensity and position, ensuring consistent radiant exposure throughout the build.",
      },
    ]),
    paragraph([
      {
        kind: "text",
        text: "In the bottom-up embodiment of ",
      },
      figure("FIG. 4", [4]),
      {
        kind: "text",
        text: " and ",
      },
      figure("FIG. 5", [5]),
      {
        kind: "text",
        text: ", exposure occurs through the transparent container bottom 21a. A layer of ",
      },
      term(
        "immiscible liquid",
        "A dense, non-reactive fluid such as heavy water or fluorocarbon liquid positioned at the bottom of the vat to prevent cured photopolymer from adhering to the container window.",
      ),
      {
        kind: "text",
        text: " 22b provides an optical window while preventing the newly solidified lamina from bonding to the container floor as elevator 29 lifts the part upward.",
      },
    ]),
    paragraph([
      {
        kind: "text",
        text: "It will be apparent that stereolithography provides an unprecedented capability to automatically extract physical three-dimensional objects from computer-generated mathematical cross-sections without tooling or molds. Accordingly, the invention is defined by the appended claims.",
      },
    ]),
    {
      kind: "heading",
      level: 2,
      text: "THE CLAIMS",
    },
    claim(1, [
      {
        kind: "text",
        text: "A system for producing a three-dimensional object from a fluid medium capable of solidification when subjected to prescribed synergistic stimulation, said system comprising: means for drawing upon and forming successive cross-sectional laminae of said object at a two-dimensional interface; and means for moving said cross-sections as they are formed and building up said object in step wise fashion, whereby a three-dimensional object is extracted from a substantially two-dimensional surface.",
      },
    ]),
    claim(2, [
      {
        kind: "text",
        text: "A system for producing a three-dimensional object from a fluid medium capable of altering its physical state in response to appropriate synergistic stimulation, said system comprising: a container which holds a body of said fluid medium, said fluid medium having a designated surface at which solidification of said fluid medium takes place; reaction means for selectively applying synergistic stimulation in a prescribed pattern to said fluid medium at said designated surface to provide a thin solid lamina representing a cross-section of said three-dimensional object, said reaction means applying said synergistic stimulation to only a thin surface layer of said fluid medium at said designated surface; and translational means for moving said object as it is formed away from said designated surface, to provide a newly formed surface of said fluid medium at said designated surface, whereby successive laminae are formed and integrated together to provide a step-wise laminar buildup of said three-dimensional object from a substantially two-dimensional surface.",
      },
    ]),
    claim(3, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: a source of impinging radiation.",
      },
    ]),
    claim(4, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: a beam of impinging radiation.",
      },
    ]),
    claim(5, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: an electron beam.",
      },
    ]),
    claim(6, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: a beam of high energy particles.",
      },
    ]),
    claim(7, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: a beam of light.",
      },
    ]),
    claim(8, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: X-rays.",
      },
    ]),
    claim(9, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: a beam of ultraviolet light.",
      },
    ]),
    claim(10, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: a jet of a reactive chemical to induce solidification of said fluid medium.",
      },
    ]),
    claim(11, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: a patterned mask overlying said designated surface for selectively applying a chemical to induce solidification of said fluid medium.",
      },
    ]),
    claim(12, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: a patterned mask overlying said designated surface for selectively exposing said surface to synergistic stimulation.",
      },
    ]),
    claim(13, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said reaction means includes: a patterned mask overlying said designated surface for selectively exposing said surface to radiation.",
      },
    ]),
    claim(14, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said translational means moves said object as it is formed away from said designated surface and further into said fluid medium.",
      },
    ]),
    claim(15, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said translational means moves said object, as it is formed away from said surface and out of said fluid medium.",
      },
    ]),
    claim(16, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein exposure to said reaction means at said designated surface is through a second non-reactive medium.",
      },
    ]),
    claim(17, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, and further including: a container for said fluid medium, wherein exposure of said designated surface to said reaction means is through the bottom of said container and a second non-reactive medium adjacent said designated surface.",
      },
    ]),
    claim(18, [
      {
        kind: "text",
        text: "A system as set forth in claim 17, wherein said second non-reactive medium is heavy water.",
      },
    ]),
    claim(19, [
      {
        kind: "text",
        text: "A system as set forth in claim 17, wherein said second non-reactive medium is ethylene glycol.",
      },
    ]),
    claim(20, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, and further including: rotational means, supplementing said translational means for altering the orientation of said object relative to said designated surface at which laminae are being formed.",
      },
    ]),
    claim(21, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein the level of said fluid medium locating said designated surface is variable.",
      },
    ]),
    claim(22, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein the level of said fluid medium locating said designated surface is maintained constant.",
      },
    ]),
    claim(23, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said translational means has multiple degrees of freedom of movement.",
      },
    ]),
    claim(24, [
      {
        kind: "text",
        text: "A system as set forth in claim 4, wherein precise focus of said beam of impinging radiation upon said designated surface is maintained.",
      },
    ]),
    claim(25, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said prescribed pattern is formed upon said designated surface by radiation emanating from the face of a cathode ray tube.",
      },
    ]),
    claim(26, [
      {
        kind: "text",
        text: "A system as set forth in claim 2, wherein said prescribed pattern is formed by light directly emanating from a phosphor image.",
      },
    ]),
    claim(27, [
      {
        kind: "text",
        text: "A system for directly producing a three-dimensional object as it is designed by a computer, comprising: deriving graphic image output from said computer, said graphic image defining successive adjacent cross-sections of the three-dimensional object designed by said computer; means for drawing upon and forming successive cross-sections, corresponding to said computer designed cross-sections of said object, at a two-dimensional interface; and means for moving said cross-sections as they are formed and building up said object in a stepwise fashion, whereby the three-dimensional object designed by said computer is automatically extracted from a substantially two-dimensional surface.",
      },
    ]),
    claim(28, [
      {
        kind: "text",
        text: "An improved system for producing a three-dimensional object from a fluid medium capable of altering its physical state when subjected to prescribed radiation, said system comprising: a body of fluid medium capable of altering its physical state; means for forming said three-dimensional object from said fluid medium by irradiating a designated surface of said medium to provide integrated, successive surface laminae at said surface, said laminae together defining said three-dimensional object.",
      },
    ]),
    claim(29, [
      {
        kind: "text",
        text: "An improved system for producing a three-dimensional object from a fluid medium, said system comprising: a body of fluid medium capable of altering its physical state in response to prescribed radiation; a radiation source for impinging said prescribed radiation in a selected pattern upon a designated surface of said fluid medium to provide only at said surface a thin solid lamina representing a cross-sectional lamina of a three-dimensional object to be formed; and means for combining successive adjacent laminae to form said three-dimensional object from said fluid medium.",
      },
    ]),
    claim(30, [
      {
        kind: "text",
        text: "A system as set forth in claim 29, wherein said radiation source includes: a beam of impinging radiation.",
      },
    ]),
    claim(31, [
      {
        kind: "text",
        text: "A system as set forth in claim 29, wherein said radiation source includes: an electron beam.",
      },
    ]),
    claim(32, [
      {
        kind: "text",
        text: "A system as set forth in claim 29, wherein said radiation source includes: a beam of high energy particles.",
      },
    ]),
    claim(33, [
      {
        kind: "text",
        text: "A system as set forth in claim 29, wherein said radiation source includes: a beam of light.",
      },
    ]),
    claim(34, [
      {
        kind: "text",
        text: "A system as set forth in claim 29, wherein said radiation source includes: a beam of ultraviolet light.",
      },
    ]),
    claim(35, [
      {
        kind: "text",
        text: "A system as set forth in claim 29, wherein said radiation source includes: X-rays.",
      },
    ]),
    claim(36, [
      {
        kind: "text",
        text: "A system as set forth in claim 29, wherein said radiation source and pattern includes: a patterned mask overlying said designated surface for selectively exposing said surface to synergistic stimulation.",
      },
    ]),
    claim(37, [
      {
        kind: "text",
        text: "A system as set forth in claim 29, wherein said radiation source and pattern includes: a patterned mask overlying said designated surface selectively exposing said surface to radiation.",
      },
    ]),
    claim(38, [
      {
        kind: "text",
        text: "A system as set forth in claim 29, wherein exposure to said prescribed radiation at said designated surface is through a second non-reactive medium.",
      },
    ]),
    claim(39, [
      {
        kind: "text",
        text: "A system as set forth in claim 29, and further including: a container for said fluid medium, wherein exposure of said designated surface to said prescribed radiation is through the bottom of said container and a second non-reactive medium adjacent said designated surface.",
      },
    ]),
    claim(40, [
      {
        kind: "text",
        text: "A system as set forth in claim 39, wherein said second non-reactive medium is heavy water.",
      },
    ]),
    claim(41, [
      {
        kind: "text",
        text: "A system as set forth in claim 39, wherein said second non-reactive medium is ethylene glycol.",
      },
    ]),
    claim(42, [
      {
        kind: "text",
        text: "A system as set forth in claim 39, wherein the level of said fluid medium locating said designated surface is maintained constant.",
      },
    ]),
    claim(43, [
      {
        kind: "text",
        text: "A system as set forth in claim 39, wherein said translational means has multiple degrees of freedom of movement.",
      },
    ]),
    claim(44, [
      {
        kind: "text",
        text: "A system as set forth in claim 39, wherein precise focus of said prescribed radiation upon said designated surface is maintained.",
      },
    ]),
    claim(45, [
      {
        kind: "text",
        text: "A system as set forth in claim 39, wherein said selected pattern is formed upon said designated surface by radiation emanating from the face of a cathode ray tube.",
      },
    ]),
    claim(46, [
      {
        kind: "text",
        text: "A system as set forth in claim 39, wherein said selected pattern is formed by light directly emanating from a phosphor image.",
      },
    ]),
    claim(47, [
      {
        kind: "text",
        text: "A system as set forth in claim 39, and further including: programmed control means for varying the pattern of said impinging radiation upon said designated surface of said fluid medium.",
      },
    ]),
  ],
};
