import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import {
  validateReviewedTranscription,
  validateReviewedTranscriptionEditorialIntegrity,
  validateReviewedTranscriptionPageAnchors,
} from "@/data/patents/sourceTextValidation";
import { stackhouseManipulatorPatent } from "@/data/patents/stackhouse-manipulator-source-bounded";
import {
  archivalEditionForPublication,
  evaluateArchivalPublicationState,
  isArchivalEditionExplicitlyWithheld,
} from "./publicationApproval";
import { stackhouseManipulatorArchivalEdition } from "./stackhouseManipulatorEdition";

describe("US 4,068,536 source boundary", () => {
  test("pins the eight-page facsimile without certifying the withdrawn draft", () => {
    const pdfPath = `${process.cwd()}/public/patents/pdfs/us-4068536-stackhouse-manipulator.pdf`;
    expect(existsSync(pdfPath)).toBe(true);

    const pdfBuffer = readFileSync(pdfPath);
    const hasher = new Bun.CryptoHasher("sha256");
    hasher.update(pdfBuffer);
    const computedDigest = hasher.digest("hex");

    expect(computedDigest).toBe("dcd6652f996f2583bb6bd39f341bac2474b08472adb931972e94137aea1b7846");
    expect(stackhouseManipulatorPatent.originalTextAsset).toBeUndefined();
    expect(stackhouseManipulatorArchivalEdition.sourcePdfSha256).toBe(
      "dcd6652f996f2583bb6bd39f341bac2474b08472adb931972e94137aea1b7846",
    );
    expect(stackhouseManipulatorArchivalEdition.completeFacsimileReviewed).toBe(false);
    expect(isArchivalEditionExplicitlyWithheld(stackhouseManipulatorPatent.id)).toBe(false);
    expect(archivalEditionForPublication(stackhouseManipulatorPatent)).toBeUndefined();
    expect(evaluateArchivalPublicationState(stackhouseManipulatorPatent).reasonCode).toBe(
      "AUDIT_FULL_SPECIFICATION_PENDING",
    );
  });

  test("preserves direct, full-sheet drawing evidence without promoting the withdrawn draft", () => {
    const figureRoot = `${process.cwd()}/public/patents/figures/us-4068536-stackhouse-manipulator`;
    const sourceSheets = [
      {
        file: "sheet-1-source-crop-v2.png",
        digest: "024e21e4cb3434111466a5bfe129012eef80b17b79277eb8becb33bb244946bd",
      },
      {
        file: "sheet-2-source-crop-v2.png",
        digest: "b55771dd6a708c55937e09db3de6bba82f8225349ff12d091d7e48d687190844",
      },
    ] as const;

    for (const sourceSheet of sourceSheets) {
      const sheetPath = `${figureRoot}/${sourceSheet.file}`;
      expect(existsSync(sheetPath)).toBe(true);
      const bytes = readFileSync(sheetPath);
      expect(bytes.subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
      expect(bytes.readUInt32BE(16)).toBe(2320);
      expect(bytes.readUInt32BE(20)).toBe(3408);
      const hasher = new Bun.CryptoHasher("sha256");
      hasher.update(bytes);
      expect(hasher.digest("hex")).toBe(sourceSheet.digest);
    }

    expect(stackhouseManipulatorPatent.drawings).toEqual([]);
    expect(archivalEditionForPublication(stackhouseManipulatorPatent)).toBeUndefined();
  });

  test("preserves the withdrawn ledger while pinning the new page-complete source-review candidate", () => {
    const transcriptRoot = `${process.cwd()}/public/patents/transcripts`;
    const withdrawnLedgerPath = `${transcriptRoot}/us-4068536-stackhouse-manipulator-reviewed.txt`;
    const cleanCandidatePath = `${transcriptRoot}/us-4068536-stackhouse-manipulator-reviewed-v2.txt`;
    const candidate = readFileSync(cleanCandidatePath, "utf8");

    expect(existsSync(withdrawnLedgerPath)).toBe(true);
    expect(existsSync(cleanCandidatePath)).toBe(true);
    expect(validateReviewedTranscription(candidate, 8)).toEqual({ valid: true });
    expect(validateReviewedTranscriptionEditorialIntegrity(candidate, 8)).toEqual({ valid: true });
    expect(
      validateReviewedTranscriptionPageAnchors(candidate, 8, [
        {
          page: 1,
          exactSourceText: "A remotely operable manipulator orients an end-effector",
          sourceRelationship: "front-page abstract",
          isBlank: false,
        },
        {
          page: 2,
          exactSourceText: "FIG. 1.",
          sourceRelationship: "drawing sheet 1",
          isBlank: false,
        },
        {
          page: 3,
          exactSourceText: "FIG. 2.",
          sourceRelationship: "drawing sheet 2",
          isBlank: false,
        },
        {
          page: 4,
          exactSourceText: "This invention relates to mechanical manipulators",
          sourceRelationship: "specification columns 1–2",
          isBlank: false,
        },
        {
          page: 5,
          exactSourceText: "shoulder 3 is rotatably mounted",
          sourceRelationship: "specification columns 3–4",
          isBlank: false,
        },
        {
          page: 6,
          exactSourceText: "spherical sector generated by the movement",
          sourceRelationship: "specification columns 5–6 and claims 1–6",
          isBlank: false,
        },
        {
          page: 7,
          exactSourceText: "7. A manipulator as recited in claim 6",
          sourceRelationship: "claims 7–18",
          isBlank: false,
        },
        {
          page: 8,
          exactSourceText: "Claim 1, line 19",
          sourceRelationship: "certificate of correction",
          isBlank: false,
        },
      ]),
    ).toEqual({ valid: true });

    const printedClaimOne = candidate
      .split("--- REVIEWED TRANSCRIPTION PAGE 7 OF 8 ---", 1)[0]
      ?.slice(candidate.indexOf("1. An improved manipulator"));
    expect(printedClaimOne).toContain("wherein the movement");
    expect(printedClaimOne).not.toContain("whereby the movement");
    expect(candidate).toContain("the word “wherein” should read --whereby--.");
  });

  test("publishes no claim decoder, drawing annotation, or reviewed-ledger assertion", () => {
    expect(stackhouseManipulatorPatent.claims).toEqual([]);
    expect(stackhouseManipulatorPatent.drawings).toEqual([]);
    expect(stackhouseManipulatorPatent.stats).toEqual({ totalClaims: 0, independentClaims: 0 });
  });

  test("keeps the public excerpt on literal facsimile text", () => {
    expect(stackhouseManipulatorPatent.originalText).toContain(
      "This invention relates to mechanical manipulators",
    );
    expect(stackhouseManipulatorPatent.originalText).toContain(
      "spot welding, spray painting, and assembly operations",
    );
    expect(stackhouseManipulatorPatent.originalText).not.toContain("2π");
    expect(stackhouseManipulatorPatent.originalText).not.toContain("singularity");
  });

  test("states the source's actual geometric boundary without invented performance", () => {
    const publicText = JSON.stringify(stackhouseManipulatorPatent);
    expect(publicText).toContain("greater than 45 degrees");
    expect(publicText).toContain("small orientation ‘holes.’");
    expect(publicText).not.toContain("exactly 45");
    expect(publicText).not.toContain("2π steradian");
    expect(publicText).not.toContain("provides singularity-free");
    expect(publicText).not.toContain("payload capacity");
  });
});
