import type {
  CuratedSpecificationEdition,
  CuratedSpecificationInline,
  CuratedSpecificationInlines,
} from "@/types/patent";

const text = (value: string): CuratedSpecificationInlines => [{ kind: "text", text: value }];
const paragraph = (inlines: CuratedSpecificationInlines) => ({
  kind: "paragraph" as const,
  inlines,
});
const claim = (number: number, value: string) => ({
  kind: "claim" as const,
  number,
  inlines: text(value),
});

const previews = {
  1: {
    src: "/patents/figures/us-4136359-wozniak-apple/fig-1-source-crop-v1.png",
    alt: "Figure 1 from US 4,136,359: the microcomputer's CPU, memory, address multiplexer, video generator, and timing generator.",
    width: 1100,
    height: 760,
  },
  2: {
    src: "/patents/figures/us-4136359-wozniak-apple/fig-2-source-crop-v1.png",
    alt: "Figure 2 from US 4,136,359: two four-bit shift registers and the phase-select multiplexer of the video generator.",
    width: 1100,
    height: 760,
  },
  3: {
    src: "/patents/figures/us-4136359-wozniak-apple/fig-3-source-crop-v2.png",
    alt: "Figure 3 from US 4,136,359: crystal-clock dividers, shift-register counter, and horizontal and vertical synchronization counters.",
    width: 1100,
    height: 875,
  },
  4: {
    src: "/patents/figures/us-4136359-wozniak-apple/fig-4-source-crop-v1.png",
    alt: "Figure 4 from US 4,136,359: the color and high-resolution waveform examples generated by the video circuit.",
    width: 1100,
    height: 720,
  },
} as const;

const figure = (number: keyof typeof previews): CuratedSpecificationInline => ({
  kind: "reference",
  text: `FIG. ${number}`,
  href: "#",
  referenceType: "figure",
  label: `Preview Figure ${number} from the US 4,136,359 source facsimile`,
  figurePreviews: [previews[number]],
});

const term = (value: string, definition: string): CuratedSpecificationInline => ({
  kind: "term",
  text: value,
  definition,
});

/**
 * Continuous, manually reviewed source reading of the seven-page US 4,136,359
 * facsimile. The grant is about video timing and digital color generation. It
 * does not claim the invented shared-DRAM/CPU-phase account that legacy copy
 * had attributed to it.
 */
export const wozniakAppleArchivalEdition: CuratedSpecificationEdition = {
  kind: "manual-react-edition",
  sourcePdfSha256: "7467256de38125790a5f1b5e4904060e8ec6aa92f33288ccc8f1ea0acb7c3fc0",
  preparedBy: "Classic Patents editorial agent (GPT-5.6)",
  preparedAt: "2026-08-18",
  completeFacsimileReviewed: true,
  blocks: [
    {
      kind: "masthead",
      lines: [
        "UNITED STATES PATENT",
        "STEPHEN G. WOZNIAK, OF CUPERTINO, CALIF., ASSIGNOR TO APPLE COMPUTER, INC., OF CUPERTINO, CALIF.",
        "MICROCOMPUTER FOR USE WITH VIDEO DISPLAY.",
        "Patent No. 4,136,359. Patented Jan. 23, 1979.",
        "Application No. 786,197. Filed Apr. 11, 1977. 8 Claims, 4 Drawing Figures.",
        "ABSTRACT.",
        "A microcomputer including a video generator and timing means which provides color and high resolution graphics on a standard, raster scanned, cathode ray tube is disclosed. A horizontal synchronization counter is synchronized at an odd-submultiple of the color subcarrier reference frequency. A “delayed” count is employed in the horizontal synchronization counter to compensate for color subcarrier phase reversals between lines for the non-interlaced fields. This permits vertically aligned color graphics without substantially altering the standard horizontal synchronization frequency. Video color signals are generated directly from digital signals by employing a recirculating shift register.",
      ],
    },
    {
      kind: "figure-sheet",
      figureLabel: "FIG. 1",
      title: "Microcomputer block diagram",
      description: [
        figure(1),
        {
          kind: "text",
          text: " is the source drawing of CPU 10, ROM 14, input/output interface 21, video generator 25, RAM 23, address multiplexer 28, and timing and synchronization generator 15.",
        },
      ],
    },
    {
      kind: "figure-sheet",
      figureLabel: "FIG. 2",
      title: "Video generator",
      description: [
        figure(2),
        {
          kind: "text",
          text: " is the source drawing of four-bit shift registers 36 and 37, phase-select multiplexer 38, and the digital lines used to form video output 26.",
        },
      ],
    },
    {
      kind: "figure-sheet",
      figureLabel: "FIGS. 3–4",
      title: "Timing generator and waveform examples",
      description: [
        figure(3),
        { kind: "text", text: " is the source timing-and-synchronization diagram; " },
        figure(4),
        { kind: "text", text: " is the source waveform graph." },
      ],
    },
    { kind: "heading", level: 2, text: "MICROCOMPUTER FOR USE WITH VIDEO DISPLAY" },
    { kind: "heading", level: 2, text: "BACKGROUND OF THE INVENTION" },
    { kind: "heading", level: 3, text: "1. Field of the Invention" },
    paragraph([
      { kind: "text", text: "The invention is for the generation of signals for " },
      term(
        "raster scanned",
        "The display is drawn as a timed sequence of horizontal lines, rather than written as a whole image at once.",
      ),
      { kind: "text", text: " video displays employing digital means." },
    ]),
    { kind: "heading", level: 3, text: "2. Prior Art" },
    paragraph([
      {
        kind: "text",
        text: "With the reduced cost of large scale integrated circuits it has become possible to provide low-cost microcomputers suitable for home use. One such use which has flourished in recent years is the application of microcomputers in conjunction with video displays for games and graphic displays. Most often an ordinary television receiver is employed as the video display means. The standard, raster scanned, ",
      },
      term(
        "cathode ray tubes",
        "Vacuum display tubes in which an electron beam scans a phosphor screen line by line.",
      ),
      {
        kind: "text",
        text: " employed in these receivers and like displays, present unique problems in interfacing these displays with the digital information provided by the microcomputer.",
      },
    ]),
    paragraph(
      text(
        "In presenting color graphics it is, of course, desirable to provide high resolution lines and to avoid “ragged” lines. In a microcomputer controlled display, typically a single frequency reference source is employed to generate the color subcarrier reference signal of 3.579545Mhz and the horizontal and vertical synchronization signals. If the frequency of the horizontal synchronization signals is to remain close to its normal frequency (i.e. 15,750hz) the horizontal synchronization means must operate at an odd-submultiple of the color subcarrier frequency. When this occurs there is a phase reversal or phase shift of the color subcarrier reference signal when compared to color control signal between each of the lines of the display. This results in ragged vertical lines unless the color signals are changed for each line. One prior art solution to this problem has been to operate the horizontal synchronization counter at an even submultiple of the color subcarrier frequency (i.e. 15,980hz). This deviation from the standard horizontal synchronization frequency typically requires manual adjustment of the receiver and for some receivers horizontal synchronization may be more difficult to maintain.",
      ),
    ),
    paragraph(
      text(
        "As will be described with the invented microcomputer, the horizontal counter operates close to its standard frequency (15,734hz). Through use of a timing compensation means, counting in the horizontal synchronization counter is delayed to compensate for the fact that the counter operates at an odd-submultiple frequency of a color reference signal. In this manner, phase reversal of the color reference signal is eliminated and sharp graphic displays are provided without complex programming.",
      ),
    ),
    paragraph(
      text(
        "In many prior art microcomputer controlled displays, color information is stored as four digital bits which are used to designate green, red, blue, and high/low intensity. The color generation means generally includes a signal generator for generating the pure color signals (CW). These pure color signals are then gated and mixed in accordance with the binary state of the four bits to provide a color signal compatible with standard television receivers. Generation of the video color signal in this manner is complex and requires a substantial amount of circuitry.",
      ),
    ),
    paragraph([
      { kind: "text", text: "The invented microprocessor includes a " },
      term(
        "recirculating shift register",
        "A chain of flip-flops whose output bits are fed back to an earlier input and clocked repeatedly through the chain.",
      ),
      {
        kind: "text",
        text: " which circulates four bits of information. In this manner video color signals are generated directly from digital information without the cumbersome generation techniques employed in the prior art.",
      },
    ]),
    { kind: "heading", level: 2, text: "SUMMARY OF THE INVENTION" },
    paragraph(
      text(
        "A microprocessor for use with a video display is described. The microprocessor includes an improved timing apparatus which provides well-defined color graphics on a standard, raster scanned, cathode ray tube. A timing reference means is employed to provide a color reference signal for the video display. A horizontal synchronization means which is synchronized to the timing reference means provides horizontal synchronization signals for the display. These signals occur at a rate which is an odd-submultiple of the color reference signal frequency. The timing apparatus includes a compensation means which is coupled to both the timing reference means and the synchronization means for periodically adjusting the horizontal synchronization signals such that these signals remain in phase relationship with the color reference signal.",
      ),
    ),
    paragraph(
      text(
        "The microcomputer also includes a unique color signal generation means which uses a recirculating shift register. This register receives digital signals representative of color from memory and circulates this data at a predetermined rate. In this manner a color signal suitable for use with a video display is generated from the digital signals.",
      ),
    ),
    { kind: "heading", level: 2, text: "BRIEF DESCRIPTION OF THE DRAWINGS" },
    paragraph([
      figure(1),
      {
        kind: "text",
        text: " is a general block diagram illustrating the invented microcomputer in its presently preferred embodiment. ",
      },
      figure(2),
      {
        kind: "text",
        text: " is a block diagram of the video generator employed in the microcomputer of ",
      },
      figure(1),
      { kind: "text", text: ". " },
      figure(3),
      {
        kind: "text",
        text: " is a block diagram of the timing and synchronization generator employed in the computer of ",
      },
      figure(1),
      { kind: "text", text: "; and " },
      figure(4),
      {
        kind: "text",
        text: " is a graph illustrating several waveforms generated by the video generator of ",
      },
      figure(2),
      { kind: "text", text: "." },
    ]),
    { kind: "heading", level: 2, text: "DETAILED DESCRIPTION OF THE INVENTION" },
    paragraph(
      text(
        "A microcomputer is disclosed which is particularly suitable for controlling color graphics on a standard, raster scanned, cathode ray tube. The described microcomputer includes a video generator which generates color signals directly from digital information, and a timing means which provides well defined color graphics, particularly in the vertical direction, without complex programming.",
      ),
    ),
    paragraph(
      text(
        "In the following description, numerous well-known circuits are shown in block diagram form in order not to obscure the described inventive concepts in unnecessary detail. In other instances, very specific details such as frequencies, number of bits, specific codes, etc., are provided in order that these inventive concepts may be clearly understood. It will be apparent to one skilled in the art that the described inventive concepts may be employed without use of these specific details.",
      ),
    ),
    paragraph([
      { kind: "text", text: "Referring now to " },
      figure(1),
      {
        kind: "text",
        text: ", the microcomputer includes a central processing unit (CPU) or microprocessor 10. While any one of a plurality of commercially available microprocessors may be employed such as the M6800 or 8080, in the presently preferred embodiment, a commercially available microprocessor, Part No. 6502, is employed. CPU 10 communicates with the data bus 18 through a bidirectional tri-state buffer 12. The CPU 10 is also coupled to the address bus 20 through a tri-state buffer 13.",
      },
    ]),
    paragraph(
      text(
        "The microcomputer, in its presently preferred embodiment, includes two memories. The first is a 12K (bytes) read-only memory (ROM) 14 which is coupled to the data bus 18. This ROM may be a mask programmable memory, EPROM or other read-only memory. The primary data storage for the computer comprises the random-access memory 23. In the presently preferred embodiment, this memory may contain 4K to 48K (bytes) and comprises commercially available dynamic MOS memories. The RAM 23 is coupled to the input/output interface means 21 via bus 30, the data bus 18 and the video generator 25.",
      ),
    ),
    paragraph([
      {
        kind: "text",
        text: "The timing signals for the microcomputer are provided by the timing and synchronization generator 15. The novel portions of this generator shall be described, in detail, in conjunction with ",
      },
      figure(3),
      {
        kind: "text",
        text: ". This generator provides timing signals for the microcomputer, and additionally, synchronization signals for the video display. Among the signals provided by the generator 15 are 2Mhz timing signals on lines 32 for the RAMs 23 and a 14.31818Mhz signal on line 33 for the video generator 25. The timing and synchronization generator 15 also provides timing signals for the decoder 16 and for the address multiplexer 28.",
      },
    ]),
    paragraph(
      text(
        "The address decoder 16 receives address signals from the address bus 20 and decodes them in a well-known manner. The address decoder 16 is coupled to the ROM 14 and to the RAM 23. Address signals are also received from the bus 20 by the address multiplexer 28 which couples these signals to the RAM 23.",
      ),
    ),
    paragraph(
      text(
        "The input/output interface means 22 provides ports which allows the microprocessor to be electrically coupled to a cassette jack or to a connector used for receiving game input/output signals. Known buffers and timing means may be employed for this purpose.",
      ),
    ),
    paragraph([
      {
        kind: "text",
        text: "The video generator 25 receives signals from the input/output interface means 21 and also from the RAM 23. This generator provides an output video signal on line 26. Video generator 25 shall be described, in detail, in conjunction with ",
      },
      figure(2),
      { kind: "text", text: "." },
    ]),
    paragraph([
      { kind: "text", text: "In the presently preferred embodiment, the entire microcomputer of " },
      figure(1),
      {
        kind: "text",
        text: " is fabricated on a single printed circuit board. This board includes connectors to allow the computer to be connected to a cassette playback means, or other devices. As will be appreciated, numerous well-known interconnections, driver means and other circuits employed in the microcomputer are not shown in ",
      },
      figure(1),
      {
        kind: "text",
        text: ". For a detailed description of circuits and interconnections which may be employed in the microprocessor of ",
      },
      figure(1),
      {
        kind: "text",
        text: ", including a transparent refresh cycle for the RAMs 23, see “A CRT Terminal Using The M6800 Family,” by Roy & Morris, Interface Age, Volume 2, Issue 2, January 1977.",
      },
    ]),
    paragraph([
      { kind: "text", text: "Referring now to " },
      figure(3),
      {
        kind: "text",
        text: ", the timing and synchronization generator (timing means) includes a frequency reference source, crystal oscillator 51. The output of oscillator 51 is coupled to a buffer 52 which provides a 14.31818Mhz signal on line 33 for the presently preferred embodiment. This signal is coupled to the video generator of ",
      },
      figure(2),
      {
        kind: "text",
        text: " as will be described, and is also coupled to the shift register counter 60 and the divider 55. The divider 55 divides the 14.31818Mhz signal by two, thereby providing a 7.15909Mhz signal on line 56. This signal is employed by the microprocessor as a timing signal, and additionally, is employed by the shift register counter 60 as a feedback synchronization signal on line 56. This signal is further divided by two, by divider 57, to provide the standard color subcarrier reference signal of 3.579545Mhz on line 58. The signal on line 58 is used in an ordinary manner by the video display and also is used as a feedback synchronization signal by the shift register counter 60.",
      },
    ]),
    paragraph([
      {
        kind: "text",
        text: "The 14.3Mhz signal on line 33 is divided by seven, by the shift register counter 60 to provide a 2Mhz signal on line 32. This signal is used by the RAMs 23 of ",
      },
      figure(1),
      {
        kind: "text",
        text: ". This 2Mhz signal is further divided by divider 62 (divided by two) to provide a 1Mhz timing signal on line 65. This 1Mhz signal in addition to being employed elsewhere in the microprocessor is used by counters 63 and 64.",
      },
    ]),
    paragraph(
      text(
        "The “divide-by-65” counter 63 is used to provide the horizontal synchronization signals for the non-interlaced display. When the maximum count is reached within the counter 63, a signal is provided on line 66 to shift register 60 and also to the vertical synchronization counter 64. The counter 64 is employed to divide this signal by 262 to provide vertical synchronization signals. In the presently preferred embodiment, the display is divided into a 65×262 array. However, 25 of the 65 horizontal character positions are employed for blanking and 70 of the 262 lines are also employed for blanking.",
      ),
    ),
    paragraph([
      { kind: "text", text: "It is apparent from " },
      figure(3),
      {
        kind: "text",
        text: " that the horizontal synchronization signals from counter 63 occur at a frequency of approximately 15,734hz. This is very close to the standard horizontal synchronization rate of 15,750hz. Each count of the counter 63 includes 3½ color cycles of the color subcarrier reference frequency; moreover, the total number of color cycles per line is a non-integer. As a result, the color subcarrier reference signal will be shifted 180° for each new line. Unless some corrective action is taken this will result in ragged vertical lines. As will now be described, compensation is provided by delaying the occurrence of the 1Mhz timing signal once for each line by a period of time corresponding to ½ cycle of the 3.58Mhz subcarrier reference signal.",
      },
    ]),
    paragraph([
      { kind: "text", text: "As shown in " },
      figure(3),
      {
        kind: "text",
        text: ", the normal counting sequence for the shift counter 60 includes seven states. When the last stage of the four stage counter contains a binary-zero, a binary-one is loaded into the second stage (position 70). The first and second stages receive the output of the second stage when the last stage contains a binary-zero. Thus, the states become 1110 after the next shift, and finally the states become 1111 as indicated by path 68. Each time a signal occurs on line 66 (every 65 cycles of the 1Mhz signal) the normal sequencing within the counter 60 is altered as shown by the extended sequence of ",
      },
      figure(3),
      {
        kind: "text",
        text: ". When a signal occurs on line 66 and when the count of 0000 is reached, the loading of the binary-one into the second stage (position 70) is delayed for two cycles of the 14.318Mhz clock. These two cycles correspond to 180° of the 3.58Mhz signal. After these two cycles, a binary-one is then loaded into the second stage, followed by the loading of binary-ones into the first and third stages. As indicated by path 69, a normal counting sequence then occurs. By extending the count within counter 60 as described, compensation occurs which provides vertical color alignment from line-to-line.",
      },
    ]),
    paragraph([
      { kind: "text", text: "Referring now to " },
      figure(2),
      { kind: "text", text: ", the video generator 25 of " },
      figure(1),
      {
        kind: "text",
        text: " includes two, four bit shift registers 36 and 37. Each of these four bit shift registers is coupled to receive four bits of data on lines 30 from the RAM 23.",
      },
    ]),
    paragraph(
      text(
        "The registers 36 and 37 receive a load signal on line 49 which causes the data on lines 30a through 30h to be shifted into the registers. The first stage of register 37 (I₀) is coupled to a multiplexer 38 by line 42. The third stage of register 37 (I₁) is also coupled to the multiplexer 38 by line 43. In a similar fashion, the first stage of the register 36 (I₂) is coupled by line 44 to the multiplexer 38, and the third stage of this register (I₃) is also coupled to the multiplexer 38 by line 45.",
      ),
    ),
    paragraph(
      text(
        "Line 44 is coupled to the fourth stage of register 36 in order that four bits of data within register 36 may be recirculated. (Registers 36 and 37 shift data from left to right, that is, toward their first stage.) The line 42 may be selectively coupled to the fourth stage of register 37 through the multiplexer 40 in order that four bits of data within register 37 may be recirculated. Line 44 may be coupled through the multiplexer 40 to the fourth stage of the shift register 37. When this occurs, the shift registers 36 and 37 operate as a single eight bit shift register.",
      ),
    ),
    paragraph(
      text(
        "Control signals designated as even/odd X (line 47) and upper/lower Y (line 48) are used to control multiplexer 38. During the color graphics mode the registers 36 and 37 operate as separate registers and data is alternately selected for coupling to line 26 by multiplexer 38. The upper/lower Y signal, during the color graphics mode, allow selection of data from either register 36 or 37. The odd/even X signal then toggles the data from the selected register by alternately selecting I₀ or I₁ if register 37 is selected, or I₂ or I₃ if register 36 is selected.",
      ),
    ),
    paragraph(
      text(
        "During the color graphics mode as presently implemented, eight bits of color information are shifted (in parallel) into the registers 36 and 37 from the RAM 23 at a 1Mhz rate. This data is recirculated within registers 36 and 37 at a rate of 14.31818Mhz by the clocking signal received on line 33. The circulation of the data bit within the registers 36 and 37 at this rate provides signals having a 3.58Mhz component and as will be described, these signals may be readily employed for providing color signals for video display.",
      ),
    ),
    paragraph(
      text(
        "In the color graphics mode, as presently implemented, each of the display characters is divided into an upper and lower color rectangle. The RAM 23 provides the four bits of color data for the upper rectangles to register 36 and for the lower rectangles to register 37. This color data for the presently preferred embodiment is coded as follows:",
      ),
    ),
    {
      kind: "table",
      caption: "Color data for the presently preferred embodiment",
      headers: [text("Color"), text("Four-bit code")],
      rows: [
        [text("Red"), text("0001")],
        [text("Pink"), text("1011")],
        [text("Blue"), text("0010")],
        [text("Light Blue"), text("0111")],
        [text("Dark Green"), text("0100")],
        [text("Light Green"), text("1110")],
        [text("Brown"), text("1000")],
        [text("Yellow"), text("1101")],
        [text("Medium Violet"), text("0011")],
        [text("Medium Blue"), text("0110")],
        [text("Medium Green"), text("1100")],
        [text("Orange"), text("1001")],
        [text("White"), text("1111")],
        [text("Gray"), text("1010")],
        [text("Gray"), text("0101")],
      ],
    },
    paragraph([
      {
        kind: "text",
        text: "When colors are coded in this manner and circulated at the rate of 14.318Mhz in the registers, video color signals compatible with standard television receivers are produced. The resultant signal for red is shown on line 71 of ",
      },
      figure(4),
      {
        kind: "text",
        text: ", light blue on line 72, brown on line 73 and gray on lines 74 and 75.",
      },
    ]),
    paragraph([
      { kind: "text", text: "Briefly referring again to " },
      figure(3),
      {
        kind: "text",
        text: ", each count of the horizontal synchronization counter 63 corresponds to 3½ cycles of the subcarrier reference signal. Thus, a 180° phase shift occurs from character-to-character with respect to the color subcarrier reference signal. This means that the color signals must be shifted by 180° by the generator of ",
      },
      figure(2),
      {
        kind: "text",
        text: ", or the coding for these signals must be alternated for odd and even horizontal character positions. In the presently preferred embodiment, a 180° phase shift for the color signals is obtained by toggling between the first or third stages of the selected registers. For example, assume that the lower portion of a character is being displayed and that the color information is thus contained within register 37. Further assume that this information is being circulated, that is, line 42 couples stage 4 to stage 1 through the multiplexer 40. For even horizontal character positions, as indicated by the signal on line 47, the phase select multiplexer 38 couples the I₀ signal to line 26. For the odd positions, a 180° phase shift is obtained by selecting the I₁ signal.",
      },
    ]),
    paragraph([
      { kind: "text", text: "During a second mode of operation the generator of " },
      figure(2),
      {
        kind: "text",
        text: " is used for providing high resolution graphics. In this case, eight bits of information are provided by the RAM 23 to the registers 36 and 37. For this high resolution mode line 42 is coupled to the video line 26 and the eight bits of data from RAM 23 are serially coupled to the video line 26 at the 14.318Mhz rate. The multiplexer 40 couples line 44 to the fourth stage of register 37 to provide a single eight bit shift register. The resultant signals are shown on lines 77 and 78 of ",
      },
      figure(4),
      {
        kind: "text",
        text: ". The signals on lines 77 and 78 provide either a green or violet display. In the presently preferred embodiment, data changes are employed to obtain the compensation provided by the multiplexer 38 during the color graphics mode.",
      },
    ]),
    paragraph(
      text(
        "Thus, a microcomputer has been disclosed which is particularly suitable for controlling a color video display. The unique timing means provides well defined vertical color lines without complicated programming changes while allowing the generation of horizontal synchronization signals at close to the standard rate. The unique video generator allows the generation of color signals directly from digital signals without the complex circuitry often employed in the prior art.",
      ),
    ),
    { kind: "heading", level: 2, text: "I claim:" },
    claim(
      1,
      "In a microcomputer for use with a video display an improved timing apparatus comprising: a timing reference means for providing a color reference signal for said video display; a horizontal synchronization means for providing horizontal synchronization signals for said display, said synchronization means coupled to said timing reference means for synchronization with said reference means such that said synchronization signals occur at an odd-submultiple of said color reference signal; timing compensation means coupled to said timing reference means and said horizontal synchronization means for adjusting said horizontal synchronization signals such that said horizontal synchronization signals are in phase relationship with said color reference signal; whereby the color graphics on a raster scanned cathode ray tube are sharply defined in the vertical direction.",
    ),
    claim(
      2,
      "The apparatus defined by claim 1 wherein said horizontal synchronization means comprises a digital counter.",
    ),
    claim(
      3,
      "The apparatus defined by claim 2 wherein said timing compensation means periodically delays counting in said counter.",
    ),
    claim(
      4,
      "The apparatus defined by claim 3 wherein said color reference signal is an approximately 3.58Mhz signal and said horizontal synchronization signals occur at a frequency of approximately 15,734Hz.",
    ),
    claim(
      5,
      "In a microcomputer for use with a video display an improved timing apparatus comprising: a horizontal synchronization counter; a timing reference means for synchronizing said counter and for providing a color reference signal, said reference signal frequency being an odd-multiple greater than the rate at which counting occurs in said counter; delay means for delaying counting in said counter when the count in said counter reaches a predetermined count, said delay means coupled to said horizontal synchronization counter and said timing reference means; whereby well-defined color graphics may be readily stored and displayed on said video display.",
    ),
    claim(
      6,
      "The apparatus defined by claim 5 including a digital divider for dividing by an odd-integer coupled between said reference means and said counter.",
    ),
    claim(
      7,
      "The apparatus defined by claim 6 wherein said digital divider includes a shift register counter and wherein the loading of digital signals in said register counter is interrupted when said predetermined count is reached.",
    ),
    claim(
      8,
      "The apparatus defined by claim 7 wherein said color reference signal is an approximately 3.58Mhz signal and said predetermined count is reached at a frequency of approximately 15,734Hz.",
    ),
  ],
};

const sourceClaim = (number: number) => {
  const source = wozniakAppleArchivalEdition.blocks.find(
    (block) => block.kind === "claim" && block.number === number,
  );
  if (source?.kind !== "claim") throw new Error(`Missing Wozniak claim ${number}.`);
  return source.inlines.map((inline) => inline.text).join("");
};

/** Each source paragraph has an authored, non-lossy engineering companion. */
export const wozniakAppleParallelReadings: Readonly<Record<number, readonly string[]>> = {
  7: [
    "The stated field is digital circuitry that creates the signals a raster-scanned display needs. It is not a general Apple II architecture claim: the source fixes attention on the timing and color-signalling problem at the television interface.",
  ],
  9: [
    "The background sets the practical setting: falling IC prices made home microcomputers possible, while ordinary television receivers became a plausible display. A raster CRT must be fed in a timing discipline that digital computer data does not automatically satisfy.",
  ],
  10: [
    "The source identifies the failure mode precisely. A single reference ordinarily supplies both the 3.579545 MHz chroma reference and sync. Keeping horizontal rate close to about 15.75 kHz requires an odd submultiple, which flips chroma phase from line to line and makes vertical color edges ragged. Running an even submultiple avoids the flip, but moves the receiver away from its standard horizontal rate.",
  ],
  11: [
    "Wozniak's stated remedy keeps the horizontal counter near 15,734 Hz and periodically delays it. That inserted timing interval compensates the color-reference phase reversal rather than asking the television receiver to accept a materially different horizontal frequency.",
  ],
  12: [
    "The prior color approach stores four bits for hue and intensity, generates separate continuous-wave color signals, then gates and mixes them. The source calls that circuitry substantial and complex; it does not discuss RAM sharing or processor-cycle theft here.",
  ],
  13: [
    "The alternative is a recirculating shift register. Four stored bits are circulated at a specified rate so that the required color signal is produced directly from digital information rather than by a separate pure-color generator and mixer network.",
  ],
  15: [
    "The summary restates the claim-level combination: a color-reference source, horizontal sync at an odd submultiple, and a compensation circuit that periodically changes the timing so sync remains in the right phase relationship to the chroma reference. The intended visible result is vertically well-defined color on a raster CRT.",
  ],
  16: [
    "A separate part of the disclosed machine is the recirculating shift-register color generator. It takes color-representative bits from memory and recirculates them at a predetermined rate, yielding a display-compatible color signal directly from those digital bits.",
  ],
  18: [
    "The drawing list assigns distinct jobs to the source figures: Figure 1 is the whole computer, Figure 2 the video generator, Figure 3 the timing/synchronization generator, and Figure 4 its waveform examples. The edition links each occurrence to the corresponding facsimile crop.",
  ],
  20: [
    "The detailed description again narrows the subject to color graphics on a conventional raster CRT. The video generator derives color from digital data, while the timing means is responsible for vertical color definition without requiring elaborate software intervention.",
  ],
  21: [
    "This is a scope warning. The patent draws familiar circuits as blocks, while spelling out selected frequencies, bit widths, and codes to make the timing idea intelligible. It says a skilled reader can implement the inventive concepts without every listed implementation detail.",
  ],
  22: [
    "Figure 1's CPU may be an M6800, 8080, or the preferred 6502. The CPU connects to data bus 18 through tri-state buffer 12 and address bus 20 through buffer 13. These are disclosed context components, not the novel claim limitations by themselves.",
  ],
  23: [
    "The preferred machine has 12K-byte ROM 14 and dynamic MOS RAM 23 that may be 4K to 48K bytes. RAM connects both through the ordinary buses and to the video generator. The source describes this arrangement, but its claims focus on timing and synchronization rather than asserting a new shared-memory protocol.",
  ],
  24: [
    "Generator 15 supplies computer timing, display synchronization, 2 MHz RAM timing on line 32, and a 14.31818 MHz signal on line 33. It also times decoder 16 and address multiplexer 28. Figure 3 is the circuit-level reference for the novel timing portions.",
  ],
  25: [
    "Address decoder 16 interprets address-bus signals and selects ROM 14 or RAM 23. Address multiplexer 28 also carries bus-20 address signals to RAM 23. The grant calls these operations well known, situating them beside the claimed timing apparatus.",
  ],
  26: [
    "The input/output interface supplies ports for a cassette jack or game input/output connector. The source expressly leaves buffers and timing means for that conventional interface unspecified.",
  ],
  27: [
    "Video generator 25 accepts signals from interface 21 and RAM 23, then sends its video output on line 26. Figure 2 expands this part of the drawing; the source treats it as a specific digital color-generation arrangement.",
  ],
  28: [
    "The preferred computer is a single circuit board with cassette-playback and other connectors. The source deliberately omits ordinary interconnections and refers readers to a 1977 M6800-terminal article for an example that includes transparent RAM refresh; that reference is not claimed as Wozniak's invention.",
  ],
  29: [
    "Figure 3 begins with oscillator 51 and buffer 52, producing 14.31818 MHz on line 33. Divider 55 halves that to 7.15909 MHz, and divider 57 halves it again to 3.579545 MHz chroma reference on line 58. Line 58 drives the display and feeds back to shift-register counter 60. The source assigns line 56 two jobs: it times the microprocessor and returns as the counter's feedback synchronization signal. It likewise describes line 33 as an input both to the Figure 2 video generator and to the counter/divider chain, so the phase relation is preserved through every stated division.",
  ],
  30: [
    "Counter 60 divides the roughly 14.3 MHz signal by seven to make a 2 MHz RAM signal, then divider 62 halves it to 1 MHz. The 1 MHz signal is used elsewhere and supplies counters 63 and 64. This chain explains why the timing relationship is tied to one crystal reference.",
  ],
  31: [
    "The divide-by-65 counter makes non-interlaced horizontal sync and signals both shift-register counter 60 and vertical counter 64 at its terminal count. Counter 64 divides by 262. The source states a 65 by 262 display array, with 25 horizontal positions and 70 lines reserved for blanking.",
  ],
  32: [
    "At approximately 15,734 Hz, counter 63 stays near the standard 15,750-Hz horizontal rate. But each count spans three and a half chroma cycles, so the chroma phase flips 180 degrees on each new line. The compensation delays one 1-MHz timing event per line by half of a 3.58-MHz cycle to repair that mismatch.",
  ],
  33: [
    "The seven-state normal sequence of counter 60 is extended once each 65 one-megahertz cycles. At count 0000, loading a one into position 70 is deferred by two 14.318-MHz clocks, equal to 180 degrees of the 3.58-MHz reference. The normal sequence then resumes, giving line-to-line vertical color alignment. In the normal path, a binary zero in the last counter stage causes a binary one to load into the second stage; the source traces successive states to 1110 and then 1111 along path 68. The delayed path 69 inserts the two-clock interval first, then loads the second-stage one and follows it with ones in the first and third stages before returning to the ordinary sequence.",
  ],
  34: [
    "The Figure 2 generator contains two four-bit shift registers, 36 and 37. Each receives four RAM data bits on the lines numbered 30. The remaining paragraphs explain how selected stages and multiplexers circulate and phase-select those bits.",
  ],
  35: [
    "Load line 49 transfers RAM lines 30a through 30h into the registers. Register 37 exposes I0 on line 42 and I1 on 43; register 36 exposes I2 on 44 and I3 on 45. Those four candidates feed phase-select multiplexer 38.",
  ],
  36: [
    "Line 44 recirculates four bits in register 36; line 42 can do the same for register 37 through multiplexer 40. Coupling line 44 through that multiplexer to the fourth stage of register 37 instead joins the two four-bit registers into one eight-bit shift register.",
  ],
  37: [
    "Even/odd X on line 47 and upper/lower Y on line 48 control multiplexer 38. In color mode the registers remain separate, upper/lower selects one register, and odd/even toggles between its first and third selected stages. That toggling is the disclosed digital way to choose phase-related output bits.",
  ],
  38: [
    "In the implemented color mode, RAM supplies eight bits in parallel at 1 MHz. Registers 36 and 37 recirculate them at 14.31818 MHz from line 33. That circulation carries a 3.58-MHz component which the circuit uses for video color.",
  ],
  39: [
    "Each display character has upper and lower color rectangles. RAM sends the upper rectangle's four color bits to register 36 and lower rectangle's bits to 37. The following table is source text, not a reconstructed modern palette: it maps every stated named color to its four-bit code.",
  ],
  41: [
    "With those codes circulating at 14.318 MHz, the source says the output is compatible with standard television receivers. Figure 4 gives waveform examples for red, light blue, brown, and the two gray patterns on lines 71 through 75.",
  ],
  42: [
    "Each horizontal-counter count again spans three and a half subcarrier cycles, producing a 180-degree phase shift from character to character. Rather than alternate the data codes, the preferred arrangement toggles the first or third stage of the selected shift register. For an even position, multiplexer 38 selects I0; for an odd position it selects I1, creating the needed phase shift.",
  ],
  43: [
    "A second mode uses the same generator for high-resolution graphics. Eight RAM bits are serially sent to video line 26 at 14.318 MHz; multiplexer 40 makes one eight-bit shift register. Figure 4 shows green or violet waveform examples, and the source says data changes supply compensation in this mode.",
  ],
  44: [
    "The conclusion ties the disclosed pieces together: timing keeps vertical color lines defined while horizontal sync stays close to its standard rate, and the video generator derives color from digital signals without the complex prior-art generation circuitry.",
  ],
};

export const wozniakAppleClaimText = sourceClaim;
