import type { Patent } from "@/types/patent";

export const spencerMicrowavePatent: Patent = {
  id: "us-2495429-spencer-microwave",
  patentNumber: "US 2,495,429",
  title: "Method of Treating Foodstuffs",
  shortTitle: "Spencer Microwave Oven & Dielectric RF Heating",
  subtitle: "High-Power Cavity Magnetron and 2.45 GHz Dielectric Molecular Agitation",
  inventors: ["Percy L. Spencer"],
  inventorLocation: "Newton, Massachusetts",
  grantDate: "1950-01-24",
  filingDate: "1945-10-08",
  era: "Electronic Era (1920–1960)",
  category: "materials",
  categoryLabel: "Microwave Engineering & Thermodynamics",
  summary:
    "The birth of microwave cooking: Percy Spencer's breakthrough invention using high-power electromagnetic energy from a cavity magnetron ($2.45\\text{ GHz}$) to heat food from within via high-frequency dielectric agitation of polar water molecules.",
  heroQuote:
    "This invention relates to the treatment of foodstuffs, and more particularly to the cooking of food by means of high-frequency electromagnetic energy...",
  originalPdfUrl: "/patents/pdfs/us-2495429-spencer-microwave.pdf",
  googlePatentsUrl: "https://patents.google.com/patent/US2495429A/en",
  usptoClassification: "H05B 6/64 (Dielectric heating / Microwave ovens)",
  originalText: `UNITED STATES PATENT OFFICE.
PERCY L. SPENCER, OF NEWTON, MASSACHUSETTS, ASSIGNOR TO RAYTHEON MANUFACTURING COMPANY, OF NEWTON, MASSACHUSETTS.

METHOD OF TREATING FOODSTUFFS.

Application October 8, 1945, Serial No. 620,919. Patent No. 2,495,429. Patented Jan. 24, 1950.

To all whom it may concern:
Be it known that I, PERCY L. SPENCER, a citizen of the United States, residing at Newton, in the county of Middlesex and State of Massachusetts, have invented certain new and useful Improvements in Methods of Treating Foodstuffs, of which the following is a specification.

This invention relates to the treatment of foodstuffs, and more particularly to the cooking of food by means of high-frequency electromagnetic energy.

Heretofore, food has been cooked by the application of heat to the exterior of the food, as by conduction from a heated surface, convection from hot air or steam, or radiation from glowing flames or heating elements. In such conventional methods, heat must penetrate slowly through the body of the food by thermal conduction from the surface to the center, requiring long cooking periods and frequently causing the exterior to become dried, scorched, or overcooked before the interior is heated to the desired temperature.

According to the present invention, food is cooked rapidly and uniformly throughout its entire volume by subjecting it to high-frequency electromagnetic waves generated by a high-power magnetron oscillator operating in the microwave region of the spectrum (for example, at frequencies between 1,000 megacycles and 10,000 megacycles, and preferably at approximately 2,450 megacycles).

The high-frequency electromagnetic waves are directed through a hollow rectangular waveguide into a closed metallic cooking enclosure or cavity containing the food to be cooked.

The alternating electric field within the cavity penetrates deep into the interior of the food, exerting high-frequency alternating electrostatic torques upon the polar water, fat, and sugar molecules contained within the cells of the food. These polar molecules are forced to oscillate back and forth billions of times per second in synchrony with the field, generating intense molecular friction and volumetric thermal heat throughout the entire mass of the food with extraordinary speed.

Referring to the drawings:
Figure 1 is a schematic perspective view showing the magnetron oscillator, waveguide launcher, and metallic cooking enclosure.
Figure 2 is a detailed cross-sectional view of the multi-cavity magnetron anode block.
Figure 3 is a diagram illustrating the dielectric loss heating mechanism in polar water molecules.`,
  plainEnglishExplanation: {
    overview:
      "For hundreds of thousands of years, humans cooked food by applying heat from the outside in (fire, ovens, pans), relying on slow thermal conduction through meat and vegetables. In 1945, while standing near an active radar cavity magnetron at Raytheon, self-taught engineer Percy Spencer noticed that a peanut butter candy bar in his pocket had melted. He placed corn kernels near the tube, which exploded into popcorn. Spencer realized that microwave radio waves penetrate food and heat it from within in seconds by shaking water molecules.",
    coreMechanism:
      "A cavity magnetron generates 2.45 GHz microwave radiation ($2,450,000,000\\text{ cycles/sec}$). These electromagnetic waves travel through a metal waveguide into a reflective metal cooking cavity. Water molecules ($H_2O$) inside food are electric dipoles (positive on hydrogen, negative on oxygen). As the microwave electric field alternates billions of times per second, the water molecules rapidly twist back and forth to align with the field, dissipating kinetic energy as friction that cooks food uniformly and in a fraction of traditional cooking time.",
    mechanicalBreakdown: [
      {
        title: "Resonant Cavity Magnetron Oscillator",
        summary: "A vacuum tube with cylindrical resonant cavities cut into a copper anode block.",
        technicalDetails:
          "Crossed electric ($E$) and magnetic ($B$) fields force emitted thermionic electrons into rotating spoke wheels (cyclotron frequency $\\omega_c = qB/m$), exciting intense electromagnetic microwave oscillations at $2.45\\text{ GHz}$.",
        archaicTerm: "Magnetron oscillator tube",
        modernEquivalent: "Microwave cavity magnetron",
      },
      {
        title: "TE10 Rectangular Metallic Waveguide",
        summary: "A hollow copper/aluminum pipe that channels microwaves into the cooking cavity.",
        technicalDetails:
          "Transmits microwaves in the fundamental transverse electric (TE10) mode with minimal attenuation ($<0.1\\text{ dB/m}$), matching impedance into the cooking box.",
        archaicTerm: "Hollow rectangular waveguide",
        modernEquivalent: "Microwave waveguide launcher",
      },
      {
        title: "Resonant Metallic Cooking Cavity & Mode Stirrer",
        summary: "A Faraday cage oven box with reflective metal walls.",
        technicalDetails:
          "Reflective steel walls create multi-mode 3D standing waves. A rotating metallic fan (mode stirrer) continually shifts standing wave hot spots to ensure even heating.",
        archaicTerm: "Metallic cooking enclosure",
        modernEquivalent: "Resonant microwave cooking cavity",
      },
    ],
    scientificPrinciples: [
      {
        principle: "Dielectric Loss & Molecular Dipole Rotation",
        formula:
          "P_v = 2 \\pi f \\cdot \\varepsilon_0 \\varepsilon'' \\cdot |\\vec{E}|^2, \\quad \\varepsilon'' = (\\varepsilon_s - \\varepsilon_\\infty) \\frac{\\omega \\tau}{1 + (\\omega \\tau)^2}",
        explanation:
          "The volumetric heating power P_v is proportional to frequency f, dielectric loss factor ε'', and the square of electric field strength E.",
      },
      {
        principle: "Microwave Penetration Depth in Foodstuffs",
        formula:
          "D_p = \\frac{c}{2\\pi f \\sqrt{2\\varepsilon'}} \\left[ \\sqrt{1 + \\left(\\frac{\\varepsilon''}{\\varepsilon'}\\right)^2} - 1 \\right]^{-1/2} \\approx 1.5\\text{ to }3.5\\text{ cm}",
        explanation:
          "At 2.45 GHz, electromagnetic waves penetrate deep into the bulk volume of food rather than stopping at the surface, eliminating thermal conduction delays.",
      },
    ],
    whyItMattersToday:
      "Spencer's patent created the modern microwave oven found in over 90% of all households worldwide, along with industrial microwave drying, plasma processing, and medical hyperthermia cancer treatments.",
  },
  claims: [
    {
      number: 1,
      isIndependent: true,
      originalText:
        "The method of treating foodstuffs which comprises subjecting the foodstuff to high-frequency electromagnetic energy within the microwave region of the spectrum to heat the foodstuff throughout its interior, substantially as described.",
      plainEnglish:
        "The master claim covering the method of cooking or heating food by subjecting it to microwave electromagnetic energy.",
      keyInnovations: [
        "Volumetric microwave cooking",
        "Dielectric polar heating of foodstuffs",
        "High-frequency electromagnetic food preparation",
      ],
    },
  ],
  drawings: [
    {
      figureNumber: "Fig. 1",
      title: "Spencer Microwave Cooking System",
      caption:
        "Schematic diagram showing cavity magnetron, power transformer, rectangular waveguide, and reflective metal cooking chamber.",
      svgType: "spencer-microwave",
      callouts: [
        {
          id: "sm-1",
          figureRef: "Fig. 1",
          label: "A",
          element: "Cavity Magnetron Oscillator",
          description: "Generates 2.45 GHz high-power microwave radiation.",
          x: 25,
          y: 40,
        },
        {
          id: "sm-2",
          figureRef: "Fig. 1",
          label: "B",
          element: "Rectangular Waveguide",
          description: "Hollow metal duct channeling microwave energy into the oven.",
          x: 45,
          y: 30,
        },
        {
          id: "sm-3",
          figureRef: "Fig. 1",
          label: "C",
          element: "Reflective Cooking Cavity",
          description: "Metal Faraday enclosure reflecting microwaves into food from all angles.",
          x: 75,
          y: 50,
        },
      ],
    },
  ],
  historicalContext: {
    problemStatement:
      "A 1940s oven cooked by heating air, then waiting for conduction ($k_{food} \\approx 0.5\\text{ W/m·K}$) to reach the center. Potatoes took the better part of an hour. Raytheon, flush with wartime magnetron contracts, needed a peacetime load for the same tube.",
    priorArtLimitations: [
      "Surface heat arrives first; the middle is still cold when the crust burns.",
      "Gas and electric ovens spend most of their energy on iron and air.",
      "No one had packaged a 2.45 GHz cavity as a kitchen appliance.",
    ],
    breakthroughInsight:
      "Spencer noticed a chocolate bar in his pocket soften near a live radar set (1945, the popcorn-and-egg demos followed). Water is a dipole. A magnetron's non-ionizing field couples to that dipole through the volume, not through the crust.",
    patentWars: [
      {
        rivalName: "Nobody serious; the fight was productization",
        rivalClaim:
          "Raytheon owned the magnetron line and Spencer's heating claims. Competitors waited for the patents and for a box that fit on a counter.",
        conflictDetails:
          "The 1947 Radarange was about six feet tall, 750 lb, and $5,000, a restaurant machine. Amana, a Raytheon subsidiary, put a 115 V countertop Radarange on sale in 1967 for $495.",
        resolution:
          "Raytheon's employee-invention gratuity was $2. Spencer became a senior vice president. The Hall of Fame plaque came later.",
        legalOutcome:
          "US 2,495,429 held. The consumer market opened when the power supply shrank, not when the claim chart changed.",
      },
    ],
    civilizationalImpact:
      "Frozen dinners, office leftovers, and a restaurant pass that can reheat without a salamander. Microwave ovens also quietly trained a generation that 2.45 GHz leaks are a door-seal problem, not a death ray.",
    funFact:
      "The third demo after candy and popcorn was an egg. It exploded in a colleague's face. Spencer kept going.",
    aftermath:
      "ISM-band 2.45 GHz exists in part because magnetron cooking needed a free slice of spectrum. Wi-Fi later moved in next door and has been arguing with popcorn ever since.",
    sideNotes: [
      "Percy Spencer had a fifth-grade formal education and more than 100 patents. Raytheon hired him as a plant expert, not as a university hire.",
      "The cavity magnetron itself is Randall and Boot (Birmingham, 1940), brought to the US by the Tizard Mission. Spencer's patent is the kitchen use, not the tube.",
    ],
  },
};
